### ISSUE TITLE
How to use licenseKey option in order to not show it to everyone

### ISSUE THREAD

**Issue by xperemiquel** [alvarotrigo/react-fullpage#106]
Hello Alvaro, 

just wondering why should I use this code into my html page so everybody can see my key?

```
new fullpage({
    licenseKey: 'YOUR_KEY_HERE'
});
```
shouldn't it be hidden instead?
Thanks a lot.

**Comment by alvarotrigo** [comment]
You can't hide front end code. That's why it is front end code :)
