### ISSUE TITLE
moveSectionDown() on child component with api via Props doesn't move Slides

### ISSUE THREAD

**Issue by JamiePoole** [alvarotrigo/react-fullpage#107]
I tried to find if this had been covered elsewhere but I imagine it's a specific case.

I'm new to React, and have a ReactFullpage element with custom components for the slides. I am then passing the fullpageApi function through the props tag.

```
<ReactFullpage
	{...fullpageOptions}
	render={ ({ state, fullpageApi }) => {
		if (!state.initialized) {
			return <div className="section" />;
		}

		return (
			<ReactFullpage.Wrapper>
			<Hero fullpageApi={fullpageApi} />
			<About fullpageApi={fullpageApi} />
			<Petition fullpageApi={fullpageApi} />
			<Stories fullpageApi={fullpageApi} />
			<Partners fullpageApi={fullpageApi} />
			</ReactFullpage.Wrapper>
		)
	}} 
/>
```
However when I now call `this.props.fullpageApi.moveSectionDown()` from my custom component -- it moves the navigation down fine, but doesn't move the actual slide itself. The next time you "scroll" it then jumps to the section the navigation thinks it's on.

```
class Hero extends React.Component {
	componentDidMount () {
		//
	}

	render () {
		return (
			<div className="section Hero">
				<img data-src={Logo} className="Logo" unselectable="on" />
				<div onClick={() => this.props.fullpageApi.moveSectionDown() }>
					<img data-src={ScrollArrow} className="ScrollArrow" alt="Scroll Down" unselectable="on" />
				</div>
			</div>
		);
	}
}
```

**Comment by alvarotrigo** [comment]
Can you please provide an isolated reproduction of the issue in codesandbox or Stackblitz or similar?

**Comment by JamiePoole** [comment]
Thanks for the response -- never used those services but I put everything into one JS file and still had the bug -- you can see it here:

https://7ky4opv79x.codesandbox.io/

If you click on the button to call "moveSectionDown()" the navigation moves down but the section render stays on Section 1. If you then scroll as normal it will jump to catch up to the navigation.

**Comment by JamiePoole** [comment]
Sorry : https://codesandbox.io/s/7ky4opv79x for the editable one

**Comment by alvarotrigo** [comment]
The provided [demo in CodeSandBox](https://codesandbox.io/s/m34yq5q0qx) works perfectly.
Play find the differences and you should be fine :)

**Comment by JamiePoole** [comment]
Yeah thats why I was confused the only difference in what I did was put it in a custom component and passed through the API object.

I think I even copy/pasted XD

It would be great if it could work within custom component sections if thats whats causing the issue but no worries if not. 

Just thought I'd raise it at the least :)

**Comment by alvarotrigo** [comment]
Your example won't work even if you remove your components and use it without them.
https://codesandbox.io/s/3ql48r881p

**Comment by JamiePoole** [comment]
Right. I'm so confused lol. But thanks for checking it out.
