### ISSUE TITLE
Missing window-defines when trying to load scrollOverflowReset extension in gatsby (SSR React)

### ISSUE THREAD

**Issue by fgreinus** [alvarotrigo/react-fullpage#109]
Hey, seems quite similar to #91.

I built a codesandbox to allow you to see what is happening. https://codesandbox.io/s/vvj0km61w7?fontsize=14

When we try to load the extension into the project (which is more complex), we receive javascript errors from the "fullpage.scrollOverflowReset.min.js" file.

See 
![image](https://user-images.githubusercontent.com/1236785/55334103-ec6f7380-5498-11e9-8358-36fffc514b6f.png)

Thanks for your help :).

**Comment by alvarotrigo** [comment]
Have you seen the other topics about it?
https://github.com/alvarotrigo/react-fullpage/issues/68
https://github.com/alvarotrigo/react-fullpage/issues/43

And the server side rendering example?
 https://github.com/alvarotrigo/react-fullpage#server-side-rendering

**Comment by cmswalker** [comment]
@fgreinus the codesandbox seems to be invalid for other reasons, can you fix and resubmit?

**Comment by fgreinus** [comment]
> @fgreinus the codesandbox seems to be invalid for other reasons, can you fix and resubmit?

Works fine for me. It just states the error when it tries to compile together the page. It's the same error in the console as it is above in my initial post.

> Have you seen the other topics about it?
> #68
> #43
> 
> And the server side rendering example?
> https://github.com/alvarotrigo/react-fullpage#server-side-rendering

Yes, I saw those. And from what I saw I did things like in the example.

**Comment by alvarotrigo** [comment]
@fgreinus I'm also getting the following errors:

```sh
 Sandbox Container: sandbox vvj0km61w7 started.
ℹ ｢wdm｣: wait until bundle finished: /
ℹ ｢wdm｣: wait until bundle finished: /
 ERROR  Failed to compile with 1 errors                              10:29:07 AM

 error  in ./src/lib/fullpage.scrollOverflowReset.min.js

Module Error (from ./node_modules/eslint-loader/index.js):

/sandbox/src/lib/fullpage.scrollOverflowReset.min.js
  10:10  error    'fp_utils' is not defined              no-undef
  10:20  error    'fp_utils' is not defined              no-undef
  11:9   error    'fullpage_api' is not defined              no-undef
  12:4   error    Expected an assignment or function call and instead saw an expression  no-unused-expressions
  21:4   warning  Unexpected use of comma operator              no-sequences

✖ 5 problems (4 errors, 1 warning)


 @ ./src/pages/index.js 13:2-52
 @ ./.cache/sync-requires.js
 @ ./.cache/app.js
 @ multi event-source-polyfill (webpack)-hot-middleware/client.js?path=/__webpack_hmr&reload=true&overlay=false ./.cache/app

✖ ｢wdm｣:
ERROR in ./src/lib/fullpage.scrollOverflowReset.min.js
Module Error (from ./node_modules/eslint-loader/index.js):

/sandbox/src/lib/fullpage.scrollOverflowReset.min.js
  10:10  error    'fp_utils' is not defined              no-undef
  10:20  error    'fp_utils' is not defined              no-undef
  11:9   error    'fullpage_api' is not defined              no-undef
  12:4   error    Expected an assignment or function call and instead saw an expression  no-unused-expressions
  21:4   warning  Unexpected use of comma operator              no-sequences

✖ 5 problems (4 errors, 1 warning)

 @ ./src/pages/index.js 13:2-52
 @ ./.cache/sync-requires.js
 @ ./.cache/app.js
 @ multi event-source-polyfill (webpack)-hot-middleware/client.js?path=/__webpack_hmr&reload=true&overlay=false ./.cache/app
ℹ ｢wdm｣: Failed to compile.
```

**Comment by alvarotrigo** [comment]
Closed until an isolated reproduction is provided as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).
