### ISSUE TITLE
Link to Gatsby example is broken

### ISSUE THREAD

**Issue by alvarotrigo** [alvarotrigo/react-fullpage#111]
The link in the docs pointing to the Gatsby example is no longer available:
https://github.com/cmswalker/react-fullpage-gatsby-setup

Should we perhaps add it into this project instead?

**Comment by alvarotrigo** [comment]
@cmswalker is this the right link to it?
https://github.com/cmswalker/gatsby_react-fullPage_Invariant-Violation-130

**Comment by cmswalker** [comment]
Sorry for the delay, this is the link for the fix: (confusing because i opened my PR against original reporters branch) https://github.com/cmswalker/gatsby_react-fullPage_Invariant-Violation-130/tree/gatsby-fix

**Comment by alvarotrigo** [comment]
Thanks for that @cmswalker. 

Perhaps we can just include the Gatsby example in a subfolder of the `example` folder ?
We could have "gatsby", "next" and "react". 
It might be easier to have them all in one same place I guess. But please let me know what you prefer to do here.  

If you are a bit busy now I can give it a try and just move the content to the examples folder.

**Comment by alvarotrigo** [comment]
Fixed in the latest release React-fullpage.js 0.1.5! ⚡️ ⚡️
