### ISSUE TITLE
Scroll To Top Button

### ISSUE THREAD

**Issue by drboboev** [alvarotrigo/react-fullpage#112]
Hi,

Can you add scroll to top button in this component? With config that enable or disable this option.

Thanks

**Comment by alvarotrigo** [comment]
You can create the button by yourself and link it to the `moveTo(0)` function of fullPage.js.


```js
<button onClick={() => fullpageApi.moveTo(0)}>
    Move down
</button>
```

**Comment by drboboev** [comment]
Your code not working, i removed `0` from `moveTo(0)` and it's worked.

`
<button onClick={() => fullpageApi.moveTo()}>
    Move down
</button>
`

Thanks.

**Comment by alvarotrigo** [comment]
My mistake, should be moveTo(1):

```js
<button onClick={() => fullpageApi.moveTo(1)}>
    Move down
</button>
```

**Comment by HenryTam-ai** [comment]
Hi,
I am creating a back to top component in my Nextjs Typescript project, and I am facing a error which saying Cannot read properties of undefined (reading 'moveTo'). The image below is my code, can anyone give me some suggestion on how to fix it ?

![image](https://user-images.githubusercontent.com/69727486/216973872-5b3f9c03-1e86-4a4e-9bb4-8d5f6f3833c4.png)
![螢幕擷取畫面 (1)](https://user-images.githubusercontent.com/69727486/216973880-235c4807-ad6b-49f5-943b-82e169c2d0e0.png)
![image (1)](https://user-images.githubusercontent.com/69727486/216973883-b9b0d4cb-8348-4fda-87e0-3c6eed29dd86.png)

Thanks a lot.

**Comment by alvarotrigo** [comment]
I don't think you can get the `fullpageApi` by importing the react package. 

Try passing the variable to the children somehow from the parent.

As an alternative, you might be able to use the global window object:

```js
window.fullpage_appi.moveTo(1, 0);
```

**Comment by alvarotrigo** [comment]
@cmswalker feel free to correct me if I'm wrong.

**Comment by HenryTam-ai** [comment]
The code is not working. 
To put it simply, I there any way I can fullpageApi outside of <ReactFullpage/> ?

**Comment by alvarotrigo** [comment]
> To put it simply, I there any way I can fullpageApi outside of ? 

Did you try passing the variable down to the children?

**Comment by HenryTam-ai** [comment]
it's worked!! I passed fullpageApi to the parent and locate it to other component.

Thank you so much for the advice!!

**Comment by alvarotrigo** [comment]
Glad it worked! 👍
