### ISSUE TITLE
scrollOverflow causes uncaught RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by pedrodim** [alvarotrigo/react-fullpage#113]
Hi!

I'm having some problems with react-fullpage and gatsby.
Just by enabling scrollOverflow: true the site crashes when navigating between pages, fullpage on both of them.

Here's a link to see the error, just try the link "go to page 2".
https://codesandbox.io/embed/5xw1ln7p9n

Disabling scrollOverflow no errors appear.

I saw #83 and #38 already but I'm using `react-fullpage` `0.1.13` so that shouldn't be the case.

**Comment by alvarotrigo** [comment]
I can not even see the codesandbox.
It shows an error saying "An unrecoverable sandbox error occurred. :-( Try refreshing the page.". 

<img width="705" alt="Screenshot 2019-04-08 at 16 58 26" src="https://user-images.githubusercontent.com/1706326/55734318-9f067f80-5a1f-11e9-9b18-817234267145.png">


Errors in Terminal are the following:
> > Sandbox Container: connected, starting sandbox 5xw1ln7p9n...
> Sandbox Container: sandbox 5xw1ln7p9n unrecoverable error "Error fetching sandbox."

Errors in JS console are the following:

> raw.svg:1 GET https://cdn.jsdelivr.net/gh/PKief/vscode-material-icon-theme@e04ab459209a1d0c9fdb7b3682e5b4aa6d586090/icons/raw.svg 404
Image (async)
(anonymous) @ GetIconURL.js:14
V @ GetIconURL.js:10
(anonymous) @ GetIconURL.js:54
g @ runtime.js:62
(anonymous) @ runtime.js:288
(anonymous) @ runtime.js:114
t @ asyncToGenerator.js:3
u @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
H @ GetIconURL.js:62
(anonymous) @ index.js:12
g @ runtime.js:62
(anonymous) @ runtime.js:288
(anonymous) @ runtime.js:114
t @ asyncToGenerator.js:3
u @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
(anonymous) @ index.js:11
(anonymous) @ index.js:20
g @ runtime.js:62
(anonymous) @ runtime.js:288
(anonymous) @ runtime.js:114
t @ asyncToGenerator.js:3
u @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
(anonymous) @ index.js:20
Ws @ react-dom.production.min.js:216
qs @ react-dom.production.min.js:220
(anonymous) @ react-dom.production.min.js:250
(anonymous) @ scheduler.production.min.js:18
Ma @ react-dom.production.min.js:250
Aa @ react-dom.production.min.js:249
Ea @ react-dom.production.min.js:248
ka @ react-dom.production.min.js:245
Js @ react-dom.production.min.js:243
Da @ react-dom.production.min.js:253
Na @ react-dom.production.min.js:253
(anonymous) @ react-dom.production.min.js:261
(anonymous) @ react-dom.production.min.js:264
La @ react-dom.production.min.js:251
Ua @ react-dom.production.min.js:264
render @ react-dom.production.min.js:266
(anonymous) @ index.js:18
Promise.then (async)
./src/embed/index.js @ index.js:16
a @ bootstrap:83
6 @ index.js:22
a @ bootstrap:83
t @ bootstrap:45
(anonymous) @ bootstrap:218
(anonymous) @ bootstrap:218
Show 16 more frames
3browserfs.rollup.js:6773 Uncaught TypeError: Cannot read property 'isReadOnly' of null
    at browserfs.rollup.js:6773
    at Worker.<anonymous> (browserfs.rollup.js:6770)
(anonymous) @ browserfs.rollup.js:6773
(anonymous) @ browserfs.rollup.js:6770

**Comment by pedrodim** [comment]
Yeah, I'm not sure what happened with the codesandbox.

I created a [minimal gatsby repo](https://github.com/pedrodim/gatsby-fullpage-maximum-call-stack) with the exact same config. The steps to reproduce are the same, just click on second page.

**Comment by alvarotrigo** [comment]
A reproduction online would come on handy :)

**Comment by pedrodim** [comment]
Try this: http://cooing-fan.surge.sh/

**Comment by alvarotrigo** [comment]
Have you tried using the latest scrollOverflow version available in the dev branch?
https://github.com/alvarotrigo/fullPage.js/blob/dev/vendors/scrolloverflow.js

**Comment by pedrodim** [comment]
Great, with this version it works just fine!
Now I just need to wait for `fullPage.js` `3.0.5`, thanks.
