### ISSUE TITLE
Pause before scrolling

### ISSUE THREAD

**Issue by agudl** [alvarotrigo/react-fullpage#115]
I cant find a way to pause the scroll for a few seconds while I do some animation.

Is this possible?

**Comment by alvarotrigo** [comment]
Please read the [the fullpage.js documentation](https://github.com/alvarotrigo/fullPage.js) regarding how to cancel the movement before it takes place: "Cancelling the scroll before it takes place"

**Comment by alvarotrigo** [comment]
And see my answer here:
https://stackoverflow.com/questions/36176677/fullpage-js-adding-a-scroll-delay

**Comment by agudl** [comment]
ReactFullpage.onLeave doesnt seem to have access to the fullpage api? Is this wrong?

**Comment by alvarotrigo** [comment]
What do you mean?

To cancel a move you just need to use `return false` in the callback. 


```js
  onLeave(origin, destination, direction) {
    console.log("Leaving section " + origin.index);
    return false;
  }
```
