### ISSUE TITLE
onClick() if something moveSectionTop()

### ISSUE THREAD

**Issue by krishnahm** [alvarotrigo/react-fullpage#116]
Hey, this must be simple but i didnot find it. Onclick i gave a function in react and if condition satisifies, i want it to scroll to the top section. else i have random code. In the html it is done by fullpageApi.moveSectionDown(), how can I do that in a different onClick function as I cannot access fullpageApi.moveSection as it is in render only.

https://codepen.io/anon/pen/gyQwqX

zSomething like this---- onClick() {if(some condition) scroll to a div}

**Comment by alvarotrigo** [comment]
Just check the [cosandbox](https://codesandbox.io/s/m34yq5q0qx) provided in the Github documentation.

**Comment by krishnahm** [comment]
I meant how to use moveSectionUp./ moveSectionDown outside of render component in a custom function. It says cannot find reactfullpageApi

**Comment by alvarotrigo** [comment]
Can you please illustrate your issue on Codesandbox?
Your codepen is confusing to me, as you are not using react in it, yet you are asking about a react-fullpage issue?
