### ISSUE TITLE
react fullpage global fullpage_api sometimes undefined sometimes not

### ISSUE THREAD

**Issue by elaineleeworld** [alvarotrigo/react-fullpage#120]
I am trying to access when the translate3d is (0px, 0px, 0px) at the top of my webpage.  I am able to access it like so  +fullpage_api.test.translate3d.split(' ')[1].split('px')[0] === 0 and have it show something.  However, sometimes I get the fullpage_api is not defined and other times it is defined. Does this have to do with fullpage js not fully loaded yet?  i notice it is undefined on initial load.  I am using @fullpage/react-fullpage": "^0.1.13" . also relatedly if i try to use window.pageYOffset instead of the translate3d,  the value is always 0 no matter what section I am on.

**Comment by cmswalker** [comment]
Would you mind providing an example for what you're trying to achieve on https://codesandbox.io/ ? You can fork this one https://codesandbox.io/s/m34yq5q0qx

**Comment by alvarotrigo** [comment]
> fullpage_api.test.translate3d.split(' ')[1].split('px')[0] === 0

Just wondering in any case, why would you want to access those values?
Are you aware you can use callbacks such as `afterLoad` and `onLeave` to fire actions when leaving to another section?
You can even use the [CSS state classes](https://github.com/alvarotrigo/fullPage.js#state-classes-added-by-fullpagejs) added on the `body` element for that same purpose.

**Comment by elaineleeworld** [comment]
thanks guys for your quick responses.  I am trying to hide an image icon when section1 is in browser view and show it in all other sections like so: 
{ +fullpage_api.test.translate3d.split(' ')[1].split('px')[0] === 0  ? (
                <img className="top-icon--hidden" src="assets/images/backtotop.png" />
              ) : (
              <div>
                <img className="top-icon" src="assets/images/backtotop.png" onClick={() => fullpage_api.moveTo("section1", 1)}   /></div>
              )}

**Comment by alvarotrigo** [comment]
@elaineleeworld then the appropiate way of doing so is by using the callbacks or state classes fullPage.js provides.

Check the [fullPage.js state classes](https://github.com/alvarotrigo/fullPage.js#state-classes-added-by-fullpagejs) or [callbacks](https://github.com/alvarotrigo/fullPage.js#callbacks) for that. 
Check [this video tutorial I did](https://www.youtube.com/watch?v=qiCVPpI9l3M) regarding css3 conditions based on fullpage.js state classes.

You can also check the callbacks example [online](https://alvarotrigo.com/fullPage/examples/callbacks.html) and on the [github examples folder](https://github.com/alvarotrigo/fullPage.js/blob/master/examples/callbacks-v3.html).

**Comment by elaineleeworld** [comment]
Thank you!  I targeted it with the fullpage state class and it worked like a charm!
