### ISSUE TITLE
TypeError: Cannot read property '0' of null

### ISSUE THREAD

**Issue by hrahimi270** [alvarotrigo/react-fullpage#121]
Hi there.
I'm using react-fullpage but it throws an error for me that I don't understand!
My code:
![image](https://user-images.githubusercontent.com/38007163/57641853-4781a380-75cb-11e9-8eea-fb1064af881c.png)
I'm fetching data with Ajax call and store it in my state. then I mapping the products from state in **ReactFullpage.Wrapper**.
As you can see, there is nothing wrong.
And this is the error:
![image](https://user-images.githubusercontent.com/38007163/57641935-75ff7e80-75cb-11e9-9528-17687572f233.png)

**Comment by alvarotrigo** [comment]
Please provide an isolated reproduction in [CodeSandBox](https://codesandbox.io/s/m34yq5q0qx), with no CSS or JS files external to fullPage.js and the minimum amount of HTML code. Use empty sections unless strictly necessary for the reproduction.

Perhaps you might find useful to read my article regarding [how to create isolated reproductions](https://alvarotrigo.com/blog/how-not-suck-at-asking-coding-questions/).

**Comment by dudesl** [comment]
@hrahimi270  I had the same issue. Don´t forget to add the class `section` in the child sections of ReactFullPage.Wrapper . This detail is in the doc but is not very clear. This had to work.

**Comment by alvarotrigo** [comment]
@dudesl thanks for clarifying what seems to be the issue!

I'll proceed to close is as there's no isolated reproduction we can work on to identify the issue.
