### ISSUE TITLE
Document/support extensions

### ISSUE THREAD

**Issue by dsbrianwebster** [alvarotrigo/react-fullpage#13]
How does one use extensions with react-fullpage? I see the link to the extensions library, but nothing in the docs about how to use them inside the components/ Interested in the fading effect one.

**Comment by alvarotrigo** [comment]
Thanks for reporting it! I'll clarify it in the docs!!

Just add the extension file and the required fullpage.js option for your extension:

```javascript
import React from 'react';
import ReactDOM from 'react-dom';
import './fullpage.scrollHorizontally.min' // if we want to use the Scroll Horizontal extension
import ReactFullpage from '@fullpage/react-fullpage';
```

Then we would just add the option `scrollHorizontally:true` in case we wanted to use such extension.

**Comment by dsbrianwebster** [comment]
lovely 👍

**Comment by alvarotrigo** [comment]
I've updated the docs with that and updated the example to also use scrollOverflow.
