### ISSUE TITLE
ScrollOverflow not working in NextJS

### ISSUE THREAD

**Issue by HektorCyC** [alvarotrigo/react-fullpage#130]
**Error**: 
```
ReferenceError: window is not defined
(anonymous function)
C:/Users/EliteBook/Documents/Projects/nova-reboot/node_modules/fullpage.js/vendors/scrolloverflow.js:2132:8
Module._compile
internal/modules/cjs/loader.js:689:30
Module._extensions..js
internal/modules/cjs/loader.js:700:10
Module.load
internal/modules/cjs/loader.js:599:32
tryModuleLoad
internal/modules/cjs/loader.js:538:12
Function.Module._load
internal/modules/cjs/loader.js:530:3
Module.require
internal/modules/cjs/loader.js:637:17
require
internal/modules/cjs/helpers.js:22:18
fullpage.js/vendors/scrolloverflow
webpack:/external "fullpage.js/vendors/scrolloverflow":1
> 1 | module.exports = require("fullpage.js/vendors/scrolloverflow");
View compiled
__webpack_require__
./webpack/bootstrap:21
  18 | // Execute the module function
  19 | var threw = true;
```
**Code:**
https://github.com/cmswalker/react-fullpage-next-example/blob/master/pages/index.js

Looks like ScrollOverflow is no working properly with NextJS.

**Comment by alvarotrigo** [comment]
Thanks for reporting it!
The issue has been treated here too: https://github.com/alvarotrigo/react-fullpage/issues/68.

We are aware of it and we are trying to figure out the solution.

**Comment by adhrinae** [comment]
@HektorCyC the example code is need to be updated.

First of all, you should not directly import vendor file [like this](https://github.com/cmswalker/react-fullpage-next-example/blob/master/pages/index.js#L5).

There is already `pluginWrapper` prop to resolve this problem.

```jsx
// It delays importing vendor file until client side rendering.
const pluginWrapper = () => {
  require('fullpage.js/vendors/scrolloverflow');
};

const Fullpage = () => (
  <ReactFullpage
	scrollOverflow={true}
    pluginWrapper={pluginWrapper}
    render={({ state, fullpageApi }) => {
      return (
        <ReactFullpage.Wrapper>
          <div className="section">
            <p>Section 1 (welcome to fullpage.js)</p>
            <button onClick={() => fullpageApi.moveSectionDown()}>
              Click me to move down
            </button>
          </div>
          <div className="section">
            <p>Section 2</p>
          </div>
        </ReactFullpage.Wrapper>
      );
    }}
  />
);
```

After deployment new version of `react-fullpage` with my PR(not sure when will be), you can just use `scrollOverflow` prop without `pluginWrapper`.

**Comment by alvarotrigo** [comment]
@adhrinae I'll release a new version this week. Probably on Wednesday!

**Comment by HektorCyC** [comment]
> @HektorCyC the example code is needed to be updated.
> 
> First of all, you should not directly import vendor file [like this](https://github.com/cmswalker/react-fullpage-next-example/blob/master/pages/index.js#L5).
> 
> There is already `pluginWrapper` prop to resolve this problem.
> 
> ```js-jsx
> // It delays importing vendor file until client side rendering.
> const pluginWrapper = () => {
>   require('fullpage.js/vendors/scrolloverflow');
> };
> 
> const Fullpage = () => (
>   <ReactFullpage
> 	scrollOverflow={true}
>     pluginWrapper={pluginWrapper}
>     render={({ state, fullpageApi }) => {
>       return (
>         <ReactFullpage.Wrapper>
>           <div className="section">
>             <p>Section 1 (welcome to fullpage.js)</p>
>             <button onClick={() => fullpageApi.moveSectionDown()}>
>               Click me to move down
>             </button>
>           </div>
>           <div className="section">
>             <p>Section 2</p>
>           </div>
>         </ReactFullpage.Wrapper>
>       );
>     }}
>   />
> );
> ```
> 
> After deployment new version of `react-fullpage` with my PR(not sure when will be), you can just use `scrollOverflow` prop without `pluginWrapper`.

Is working, thanks!

**Comment by alvarotrigo** [comment]
Let's keep the issue open until it gets released :)

**Comment by alvarotrigo** [comment]
Fixed in the latest release React-fullpage.js 0.1.5! ⚡️ ⚡️
