### ISSUE TITLE
full page js licence in react

### ISSUE THREAD

**Issue by anilSimon123** [alvarotrigo/react-fullpage#131]
Hi,

I am relatively new to react and I just bought the licence for full page js. Can you please provide me instructions on how to add the licence key? 

I saw the posts :
 https://github.com/alvarotrigo/fullPage.js/issues/3452
https://github.com/alvarotrigo/react-fullpage/blob/master/example/src/index.js#L17

however, I am not seeing where the licence key should be passed. I tried,

     componentDidMount(){
       console.log('component mounted');
         new fullpage({
           licenseKey: 'XXXX-XXXX-XXXX-XXXX'
       });
     }

which is definitely stupid and the code did, of course, give me an error, but was feeling helpless. If you can please tell me where to exactly place it, it would be amazing.

**Comment by alvarotrigo** [comment]
As detailed in the [the fullpage.js documentation](https://github.com/alvarotrigo/fullPage.js):

> **licenseKey:** (default null). This option is compulsory. If you use fullPage in a non open source project, then you should use the license key provided on the purchase of the fullPage Commercial License. If your project is open source, contact me with a link to its repository and I'll provide you a license key. Please read more about licenses here and on the website. For example:

```js
new fullpage({
    licenseKey: 'YOUR_KEY_HERE'
});
``` 

It is just another option. 
You can see how to add options in react-fullpage in the examples folder or the codesandbox:
https://codesandbox.io/s/m34yq5q0qx

**Comment by alvarotrigo** [comment]
> I saw the posts :
> [alvarotrigo/fullPage.js#3452](https://github.com/alvarotrigo/fullPage.js/issues/3452)
> https://github.com/alvarotrigo/react-fullpage/blob/master/example/src/index.js#L17

See the fullpage.js options declared in these lines:
https://github.com/alvarotrigo/react-fullpage/blob/master/example/src/index.js#L113

**Comment by anilSimon123** [comment]
> > I saw the posts :
> > [alvarotrigo/fullPage.js#3452](https://github.com/alvarotrigo/fullPage.js/issues/3452)
> > https://github.com/alvarotrigo/react-fullpage/blob/master/example/src/index.js#L17
> 
> See the fullpage.js options declared in these lines:
> https://github.com/alvarotrigo/react-fullpage/blob/master/example/src/index.js#L113

sorry, i dont see the licence key being passed in line 113

**Comment by alvarotrigo** [comment]
Just add a new line below:

```js
licenseKey: 'YOUR_KEY'
```

It is just another option more :)

**Comment by anilSimon123** [comment]
> Just add a new line below:
> 
> ```js
> licenseKey: 'YOUR_KEY'
> ```
> 
> It is just another option more :)

Yess! working now with no console warnings! 
Thanks a bunch! this is what i was looking for! :-)

**Comment by alvarotrigo** [comment]
No problem! Glad you got it working!

**Comment by alvarotrigo** [comment]
I've updated [the docs](https://github.com/alvarotrigo/react-fullpage/tree/dev) with examples of where to add the `licenseKey` and fullPage.js options. 
I hope that makes it easer from now.

**Comment by High-Impact** [comment]
Hello, I was getting this error "fullPage: Fullpage.js version 3 has changed its license to GPLv3 and it requires a `licenseKey` option. Read about it here:" so I went and bought the standard license as I'm a one man show.

Here is my code:
`new fullpage('#cs-content', {
	//options here
	autoScrolling:true,
	scrollHorizontally: true,
  sectionSelector: '.x-section',
  licenseKey: 'XXX....-XXX...-XXX...-XXX...'
});

//methods
fullpage_api.setAllowScrolling(false);`

How ever, I'm still getting the error. I'm curious if I'm doing something wrong, or if the system just takes a day or so to update new licenses? 

Cheers,
Jonathan

**Comment by alvarotrigo** [comment]
@High-Impact any url you can share with us?

**Comment by High-Impact** [comment]
https://nw.stg.highimpact.design/

**Comment by High-Impact** [comment]
It's a WordPress stack (Just now noticing this thread is for React specifically) 

I'm referencing [`master/dist/fullpage.min.js`](https://github.com/alvarotrigo/fullPage.js/blob/master/dist/fullpage.min.js)

**Comment by alvarotrigo** [comment]
You might be importing fullpage.js multiple times.
The code is minified so difficult to know.

Also, many other errors reported on the fullpage.js inspector:
https://alvarotrigo.com/fullPage/inspector/?url=https://nw.stg.highimpact.design
![image](https://user-images.githubusercontent.com/1706326/101495835-4fe9be00-3969-11eb-80be-6331b32e4e87.png)

**Comment by High-Impact** [comment]
Thank you!  I just updated the code to the version that came with the license, and it's working now.

**Comment by mani1911** [comment]
Can I get a license key please? Im working on a club project and the repo is provate

**Comment by hanakirana25** [comment]
Hi, i just bought a commercial license key of fullpage.js for my non open source ReactJS project.

I have some issue, although i've put the license key exactly like the reference https://codesandbox.io/s/m34yq5q0qx?file=/src/index.js 
it still gives an error :
![Group 16370](https://github.com/alvarotrigo/react-fullpage/assets/49090486/debface7-f7bc-408e-b65f-887ef5d22a13)


my code when i place the license key:
![image](https://github.com/alvarotrigo/react-fullpage/assets/49090486/d5c8d2eb-6438-463d-b269-4bd2b6e4a434)



I installed the fullpage.js from npm command : `npm i @fullpage/react-fullpage`

**What should I do to remove the error console message?** 

Kindly provide me the solution for this issue. Thanks in advance.

**Comment by alvarotrigo** [comment]
> I have some issue, although i've put the license key exactly like the reference https://codesandbox.io/s/m34yq5q0qx?file=/src/index.js
> it still gives an error :

Make sure to use the latest react-fullpage version 01.40.

It looks like you are using an old version that uses  fullPages.js  version 3 instead of version  4.

**Comment by hanakirana25** [comment]
I've update the version and now it works fine. Thank you!
