### ISSUE TITLE
"Demo Online" doesn't match the CodeSandBox link

### ISSUE THREAD

**Issue by suntour** [alvarotrigo/react-fullpage#134]
Hey,

I'm not sure if this is intentional or not, but the CodeSandBox link does not replicate the "Demo online" website
![image](https://user-images.githubusercontent.com/37424999/60775554-3304e780-a0f2-11e9-90cf-233a07a7bc65.png)

It appears to be missing the navbar and other components.

Thanks,
suntour

**Comment by suntour** [comment]
Additionally, the Move top button doesn't work in: https://codesandbox.io/s/m34yq5q0qx

**Comment by alvarotrigo** [comment]
Thanks for reporting it! 
We'll definitely take a look at that!

**Comment by alvarotrigo** [comment]
> fullpageApi.moveTo(0,0)}
> and
> fullpageApi.moveTo(0,0)}

I've updated the codesandbox.
Sections index start by 1 as detailed in the [the fullpage.js documentation](https://github.com/alvarotrigo/fullPage.js). So it should be:

```
<button onClick={() => fullpageApi.moveTo(1,0)}>
```

**Comment by alvarotrigo** [comment]
> I'm not sure if this is intentional or not, but the CodeSandBox link does not replicate the "Demo online" website

That's totally intentional :)
The codesandbox is just a quick demo, which is ideal to recreate possible issues, I don't want to include it it much additional CSS.

**Comment by diegomtzg** [comment]
How are the navbar tabs implemented in the demo online? I'm looking to do something similar in my own site :)

**Comment by alvarotrigo** [comment]
These ones?
![image](https://user-images.githubusercontent.com/1706326/102063276-1b0cb980-3df6-11eb-9861-505a37e478d7.png)


That's not a fullPage.js question but rather a CSS / JS one so I would recommend you to ask in another place where they'll be able to answer you much better such as stackoverflow.com
