### ISSUE TITLE
fullpage_api not defined

### ISSUE THREAD

**Issue by lookitskris** [alvarotrigo/react-fullpage#146]
running example in react-fullpage/examples/react/src/index.js gives "fullpage_api is not defined (line 80)"

I tried to fix it but I couldn't figure out how to pass the api to the Menu element. If the Menu element is defined within ReactFullpage component and passed as props it works but the menu does not remain anchored to the top of the page.

**Comment by alvarotrigo** [comment]
I can't see any error in the example available.
Make sure to follow the instructions regarding how to build it or serve it:
https://github.com/alvarotrigo/react-fullpage/tree/master/examples/react

Use `npm run build:dev` from the root folder.

**Comment by lookitskris** [comment]
I took the code from index.js and put it into a fresh blank create-react-app template to try and create a minimal starting point. This might be my inexperience with react, but I can't figure out how to get the Menu element to reference the fullpage_api class. The only way I've mananged to do it is to put the Menu inside ReactFullPage and pass the api as a prop, this works but now that the menu is part of the full page it scrolls along with the rest of the site. What am I doing wrong?

**Comment by alvarotrigo** [comment]
Working as expected when modifying the [codesandbox provided in the docs](https://codesandbox.io/s/m34yq5q0qx) and adding the following body with a fixed button using the fullpage_api:


```html
<body>
	<button class="test" onclick="fullpage_api.moveSectionDown()" style="position:fixed; top: 20px; left:20px;z-index:999;">Click here</button>
	<div id="react-root"></div>

	</div>
	<script src="main.js"></script>
</body>
```

**Comment by lookitskris** [comment]
ok, but now try doing something like that from inside the Menu in this sample and observe what happens (the provided codesandbox has no menu, which is different to this sample)

**Comment by alvarotrigo** [comment]
But button I created emulates a menu. 
What would be the difference with your "menu"?

**Comment by alvarotrigo** [comment]
> ok, but now try doing something like that from inside the Menu in this sample and observe what happens (the provided codesandbox has no menu, which is different to this sample)

Can you try reproducing your issue in the codesandbox and creating a fork so we can see what you mean?

**Comment by lookitskris** [comment]
cheers! going down this path I figured it out - I had my import pointing to the wrong place, but I also had to disable the linter on the lines with api calls as it was saying it didnt exist.

**Comment by alvarotrigo** [comment]
Glad you figured it out!
