### ISSUE TITLE
readme file links to 404

### ISSUE THREAD

**Issue by MariusMeiners** [alvarotrigo/react-fullpage#150]
### Description
https://github.com/alvarotrigo/react-fullpage
in this projects readme file if you scroll down to examples and then click on the link for "In-depth examples can be found here" (link on here) you get a 404, probably the resource has moved?

**Comment by alvarotrigo** [comment]
Thanks for reporting it!
We'll definitely solve that! I'll mark it as an enhancement!

**Comment by fireairforce** [comment]
But the error in the master still remain...

**Comment by alvarotrigo** [comment]
@fireairforce here's the right link:
https://github.com/alvarotrigo/react-fullpage/tree/master/examples

The was fixed on the dev branch, so it will get merged on the next release.

**Comment by alvarotrigo** [comment]
Fixed in 0.1.17! ;I
