### ISSUE TITLE
Is there anyway to create a section with a slide on one half and text/background on the other half?

### ISSUE THREAD

**Issue by crj2804** [alvarotrigo/react-fullpage#151]
I have a second section (my about page) with slides being the entire section.   I wanted to create 2 separate halves with the left half being the slides and the other right half being the text/about us.  I've tried wrapping divs around each half and I got it to work and the slide is on one half of the page BUT the "next" slide arrow is still on the right side of the entire section instead of it just being on the left-side half.  Any help?

**Comment by alvarotrigo** [comment]
Unfortunately that's not something provided by fullPage.js.
