### ISSUE TITLE
scrollOverflow:true not work

### ISSUE THREAD

**Issue by usulla** [alvarotrigo/react-fullpage#16]
Hi!

The plugin is grateful, thank you!
But there was one problem.
Property scrollOverflow:true not work..
Demo: http://mydemo2.landmary.ru

**Comment by alvarotrigo** [comment]
Working fine in the CodeSandBox:
https://codesandbox.io/s/91xr7868no

Can you please provide an isolated reproduction in codesandbox or similar?
Make sure you use the latest react-fullpage version 0.0.6

**Comment by usulla** [comment]
I set the height of section 100vh, so it did not scroll. 
Removed the height and all work.
Thank you!

**Comment by alvarotrigo** [comment]
Glad you fixed it!
