### ISSUE TITLE
Can you provide source code for https://alvarotrigo.com/react-fullpage/?

### ISSUE THREAD

**Issue by liucien** [alvarotrigo/react-fullpage#161]
### Description
Because of the existence of react-router, the anchor can not be located.Such as `<a href="#page1">`
no work.

**Comment by alvarotrigo** [comment]
Can you please explain the issue in detail? 

Please provide an isolated reproduction in [Codesandbox](https://codesandbox.io/s/m34yq5q0qx) with no CSS or JS files external to fullPage.js and the minimum amount of HTML code. Use empty sections unless strictly necessary for the reproduction.

Perhaps you might find useful to read my article regarding [how to create isolated reproductions](https://alvarotrigo.com/blog/how-not-suck-at-asking-coding-questions/).

**Comment by claytonfinney** [comment]
Seconding this! The demo site's example seems like it would be a great resource.

**Comment by alvarotrigo** [comment]
@claytonfinney can you provide an isolated reproduction of the issue in codesandbox?

**Comment by liucien** [comment]
I`m use `fullpageApi.moveTo()`  Solve my problem
