### ISSUE TITLE
How do i access fullpageApi to move section up or down for navigation outside render

### ISSUE THREAD

**Issue by caberg** [alvarotrigo/react-fullpage#166]
you can see my code here https://codesandbox.io/s/falling-fog-bxhct

you can look at line 15 at App.js, i'm passing prop from child component but it just doesnt work, what goes wrong?

any help will be appreciated. thx

**Comment by alvarotrigo** [comment]
See the  example here:
https://codesandbox.io/s/m34yq5q0qx

**Comment by caberg** [comment]
thanks for fast reponse, sorry for my ignorance but i only see fullpageApi inside render in example code.
what i want is call fullpageApi outside fullpage component (you can see on my code at line 15 in App.js)

im new in reactjs, can you please tell me what line of code i must look at example url? thx before

**Comment by alvarotrigo** [comment]
Use the global `fullpage_api` object from the JS library:

```html
<button onClick={() => fullpage_api.moveSectionDown()}>
```

**Comment by danOcoder** [comment]
Hey this might be a stupid question but how would you import or get access to the `fullpage_api` object in this situation?

**Comment by alvarotrigo** [comment]
`fullpage_api ` is a property on the `window` object. 
Just do `window.fullpage_api` when running it on the client side.

**Comment by Anu-Ujin** [comment]
@alvarotrigo sorry can I ask you something? I return react component inside the section, not just text. but its content not showing. It's not possible or am I missing something? 

When I inspect it my component shows below the" fp-tableCell" div tag

**Comment by alvarotrigo** [comment]
@Anu-Ujin can you please open a new issue and provide a link to codesandbox with your issue? Thanks!

**Comment by codeninja-top** [comment]
How can I access fullpage_api outside render props of ReactFullPage component?

**Comment by alvarotrigo** [comment]
> How can I access fullpage_api outside render props of ReactFullPage component?

Have you tried using `fullpage_api`?
For example: `fullpage_api.moveSectionDown()`
