### ISSUE TITLE
Can not use Horizontal Scroll extension after purchasing license

### ISSUE THREAD

**Issue by f4z3k4s** [alvarotrigo/react-fullpage#169]
I've spent like 3 hours figuring out how to use the horizontal scrolling extension with React and I had no luck. I purchased both the fullpage.js license and the horizontal scroll extension license. Either the documentation is bad or I am totally missing something.

The relevant part of the documentation:
```js import React from 'react';
import ReactDOM from 'react-dom';
import ReactFullpage from '@fullpage/react-fullpage';

// NOTE: if using fullpage extensions/plugins put them here and pass it as props
const pluginWrapper = () => {
  require('./statics/fullpage.scrollHorizontally.min');
};

const Fullpage = () => (
  <ReactFullpage
    pluginWrapper = {pluginWrapper}

    //fullpage options
    licenseKey = {'YOUR_KEY_HERE'}
    scrollingSpeed = {1000} /* Options here */
    scrollHorizontally = {true}  /* Because we are using the extension */
    scrollHorizontallyKey = {'YOUR KEY HERE'}

    render={({ state, fullpageApi }) => {
      return (
        <ReactFullpage.Wrapper>
          <div className="section">
            <p>Section 1 (welcome to fullpage.js)</p>
            <button onClick={() => fullpageApi.moveSectionDown()}>
              Click me to move down
            </button>
          </div>
          <div className="section">
            <p>Section 2</p>
          </div>
        </ReactFullpage.Wrapper>
      );
    }}
  />
);
```
I would like to highlight this:
```js
const pluginWrapper = () => {
  require('./statics/fullpage.scrollHorizontally.min');
};
```
How am I supposed to have this `fullpage.scrollHorizontally.min.js` file? I thought I might be provided with it when I purchase the extension but I only had the license key there. I've read through every documentation and I can not figure out how to make this extension work.

**Comment by f4z3k4s** [comment]
Whoops, I just found a `Download` button in the email. Thank you, sorry.

**Comment by alvarotrigo** [comment]
> Whoops, I just found a `Download` button in the email. Thank you, sorry.

:) Glad you found it!
Any suggestion to improve the docs for others that might find themselves in your same situation?
