### ISSUE TITLE
Support for SSR / Next.js?

### ISSUE THREAD

**Issue by danielrvoigt** [alvarotrigo/react-fullpage#17]
Was wondering if there was a workaround for making react-fullpage work with an SSR framework like Next.js?

The error I'm getting when I imported react-fullpage in a Next app was that 'window' was undefined, which is understandable since 'window' isn't available for SSR.

**Comment by cmswalker** [comment]
Due to the way `fullpage.js` instantiates itself, it must be within a browser environment. The window must be present in order to build 100% vh slides and set event listeners. It seems like there would be little value in SSR for this as it would need to be rehydrated immediately on `document.ready` in order to build the proper layout.

If you need content for SEO purposes would it be feasible to render your content without being wrapped in fullpage on the backend, then wrapping it in fullpage on the frontend when rehydrating?

**Comment by cmswalker** [comment]
Alternatively, we can do what the previous library did and enforce that window be a required prop, this would basically return a stub/noop on the backend and a full render on the frontend. Would this work @danielrvoigt ?

**Comment by cmswalker** [comment]
See https://github.com/alvarotrigo/react-fullpage/pull/24

**Comment by JulianJorgensen** [comment]
@cmswalker I just checked out the branch `ssr-error` and when I use it with Next.js i still get the original error (window not defined).

I'm very excited to use this library, looks very promising!

**Comment by cmswalker** [comment]
The branch doesn't have the compiled library. So if you check that out and
link it you'd need to require the component directly vs the one resolved
from package.json.  Once merged it'll get rebuilt and released

**Comment by JulianJorgensen** [comment]
@cmswalker Pretty sure I did just that. I import it in my repo using `import ReactFullpage from '../../react-fullpage/dist/react-fullpages';` which is linking to the fork with `ssr-error` branch checked out and built.
I just ran `yarn && yarn build`

**Comment by cmswalker** [comment]
@JulianJorgensen @danielrvoigt since this was a non breaking change I went ahead and published the patch @0.0.7  Give it a shot

**Comment by JulianJorgensen** [comment]
@cmswalker thanks a bunch! However, as I suspected I do still get the original error @danielrvoigt pointed out: `window is not defined` when using Next.js.
![screen shot 2018-09-02 at 8 50 39 pm](https://user-images.githubusercontent.com/46347/44959641-042a4d80-aef2-11e8-8e13-de5a82b90ee1.png)

**Comment by cmswalker** [comment]
Hmm. I tested this and it worked fine without window. I'll test again with
some next boilerplate. Just to be sure you're positive you aren't npm
linked to the old version right?

**Comment by JulianJorgensen** [comment]
@cmswalker Yes I even just deleted node_modules and installed again to be sure. I'm using v 0.0.7.
Thanks for looking into this! Really appreciated!

**Comment by cmswalker** [comment]
@JulianJorgensen ah i made some additional changes, try v0.0.8 and check out https://github.com/alvarotrigo/react-fullpage#server-side-rendering

**Comment by bar0191** [comment]
I've been keeping an eye on this issue since I'm using NextJS as well. I can say on my end things seem to be working now, and can render the react fullpage component with NextJS using the import you mentioned in the readme. I will continue to develop with it in NextJS and keep you posted.

**Comment by cmswalker** [comment]
great thanks, going to mark as resolved for now

**Comment by n0umankhan** [comment]
@cmswalker thank you so much the effort you and @alvarotrigo are putting for us. Shall i request you another feature ? can you add SSR support not only for next.js or gatsby.js but also for other frameworks. In my case, I'm using react-razzle. I'm just stuck here my content is not visible to bots after using fullpage wrapper.

**Comment by n0umankhan** [comment]
@alvarotrigo can you please help on the above comment ?

**Comment by alvarotrigo** [comment]
@n0umankhan can you please create a new issue with the suggestion?
I'll mark it as a possible enhancement.
