### ISSUE TITLE
how to disable mouse scroll 

### ISSUE THREAD

**Issue by caberg** [alvarotrigo/react-fullpage#170]
tried this so many time but cant figure out how to disable mouse scroll

how i do that?

**Comment by alvarotrigo** [comment]
Use `setAllowScrollling` method.
More info on the fullpage.js docs:
https://github.com/alvarotrigo/fullPage.js#setallowscrollingboolean-directions

**Comment by caberg** [comment]
already tried that but no avail, yes it can with onclick event but how i put this to run immediately

**Comment by alvarotrigo** [comment]
Just put it after the initialisation.

**Comment by alvarotrigo** [comment]
Or on the `afterRender` callback.

**Comment by caberg** [comment]
<ReactFullpage

	//fullpage options
	licenseKey = {'OPEN-SOURCE-GPLV3-LICENSE'}
        scrollingSpeed = {1000}
	keyboardScrolling = {false}
	fixedElements = {'#prev-next, #fixed-menu'}
	onLeave = {this.onLeave.bind(this)}
	afterRender = {() => fullpageApi.setAllowScrolling(false) }

this return fullpage_api is not defined

**Comment by alvarotrigo** [comment]
Adding a small delay seems to be necessary for some reason, see the whole code here:
https://codesandbox.io/s/react-fullpagejs-example-o29q7

**Comment by caberg** [comment]
thanks a lot, it failed in my backend but dunno when i paste my code to sandbox its works

will figure what the hell is happen to my backend. thx again

**Comment by caberg** [comment]
wait a sec, it has same error with me. look at your sandbox https://codesandbox.io/s/react-fullpagejs-example-o29q7

it's same with me
'fullpage_api' is not defined. (no-undef) eslint
'fullpage_api' is not defined. (no-undef) eslint
'fullpage_api' is not defined. (no-undef) eslint

it's looks like mouse scroll has been stopped but it's actually an error . yes?

**Comment by alvarotrigo** [comment]
I don't see any error :)

**Comment by caberg** [comment]
![chrome_3vyfZtTKFm](https://user-images.githubusercontent.com/2444037/68589756-589a6700-04bf-11ea-88f4-9f631c93276e.png)

**Comment by alvarotrigo** [comment]
That's ok, just remove the `fullpage_api` from the console logs I  added. Only kee the one in the setTimeout function.

**Comment by caberg** [comment]
unfortunately still have same error with this

fullpage_api.setAllowScrolling(false);

and i confirm that you can't call fullpage_api outside ReactFullpage wrapper

**Comment by alvarotrigo** [comment]
Can you provide an isolated reproduction of it in codesandbox?

**Comment by EslimDaga** [comment]
> Adding a small delay seems to be necessary for some reason, see the whole code here: https://codesandbox.io/s/react-fullpagejs-example-o29q7

I tried this and it worked for me. Thanks @alvarotrigo
