### ISSUE TITLE
Conditional rendering error

### ISSUE THREAD

**Issue by baeharam** [alvarotrigo/react-fullpage#172]
I implemented 2 pages and applied conditional rendering to second page. However, when I change component in "section" of fullpage, it makes unknown error. How can I apply conditional rendering for react-fullpage?

### App.js

```
import React, { useState } from 'react';
import Home from './components/Home';
import Input from './components/Input';
import { GlobalStyle } from './styles/common';
import ReactFullpage from '@fullpage/react-fullpage';

const App = () => {

  return (
    <>
      <ReactFullpage 
        render={({ state, fullpageApi }) => {
          return (
            <ReactFullpage.Wrapper>
              <Home />
              <Input />
            </ReactFullpage.Wrapper>
          );
        }}
      />
      <GlobalStyle />
    </>
  );
};

export default App;
```

### Input.js (Second page for conditional rendering)

```
import React, { useState } from 'react';
import { StyledContainer } from '../styles/styleInput';
import InputForm from './InputForm';
import InputLoading from './InputLoading';

const Input = () => {
  const [state, setState] = useState('none');

  const renderForState = () => {
    switch(state) {
      case 'none': return <InputForm setState={setState} />;
      case 'loading': return <InputLoading />;
    }
  };

  return (
    <StyledContainer className="section">
      {renderForState()}
    </StyledContainer>
  );

};

export default Input;
```

When the processing in `InputForm.js` is done, state of `Input.js` is changed and component is changed into `InputLoading.js` by `renderForState` function. What is wrong with this?

**Comment by alvarotrigo** [comment]
Can you please provide an isolated reproduction in [Codesandbox](https://codesandbox.io/s/m34yq5q0qx) with no CSS or JS files external to fullPage.js and the minimum amount of HTML code? Use empty sections unless strictly necessary for the reproduction.

**Comment by alvarotrigo** [comment]
@baeharam did you manage to solve your issue?

**Comment by VGMQT** [comment]
@alvarotrigo It seems that when we use { useState } and change the state of any variable, different errors may appera stopping fullpage.js from working. Do you know how to use { useState } properly with your plugin? Maybe, I'm just doing something wrong. Trying to resolve this right now with no success.

**Comment by VGMQT** [comment]
Nevermind, everything is fine. The main idea here is not to change the sections divs and their classnames, because fullpage.js need them to do it's stuff. When we update (add/remove) a classname for a section or section itself, we delete fullpage.js classnames from it's dedicated section. At least this was my problem. Hope, it'll help someone.

**Comment by alvarotrigo** [comment]
@VGMQT good to know you fond the issue :)
