### ISSUE TITLE
this error occurred when I installed with  npm i @fullpage/react-fullpage 

### ISSUE THREAD

**Issue by kaierrao** [alvarotrigo/react-fullpage#174]
![image](https://user-images.githubusercontent.com/19768144/71073522-8445f680-21bb-11ea-9a12-aca9bd2d5672.png)

**Comment by alvarotrigo** [comment]
Steps to reproduce the issue?

Working perfectly on the [codesandbox](https://codesandbox.io/s/m34yq5q0qx).

**Comment by kaierrao** [comment]
It may be that I have installed this version  0.1.16.  
Below is my configuration in package.json：
![image](https://user-images.githubusercontent.com/19768144/71139632-b4d47180-2249-11ea-9aa2-4d407ca4ec9a.png)

**Comment by alvarotrigo** [comment]
Try with 0.1.17 then :)
We only provide support for the latest version in any case.

**Comment by kaierrao** [comment]
Thanks a lot
