### ISSUE TITLE
echarts legend event can't work when use fullPage.js overflowScroll:true

### ISSUE THREAD

**Issue by funlee** [alvarotrigo/react-fullpage#183]
I write a [ demo](https://codesandbox.io/s/vigilant-franklin-wnntn), and online address : https://codesandbox.io/s/vigilant-franklin-wnntn

my question is echarts's legend event can't work.

![image](https://user-images.githubusercontent.com/20290821/79316555-0c07fb80-7f37-11ea-9745-cb0173573e7b.png)

I guess the reason is :https://github.com/alvarotrigo/fullPage.js/wiki/FAQ---Frequently-Answered-Questions#my-javascriptjquery-events-dont-work-anymore-when-using-fullpagejs

but,I don't know how to use afterRender to fix this problem.

**Comment by alvarotrigo** [comment]
They work for me. What browser are you using?

**Comment by funlee** [comment]
> They work for me. What browser are you using?

chrome

![image](https://user-images.githubusercontent.com/20290821/79409158-bfbcca00-7fcf-11ea-95b4-ed0c66f4a0f0.png)

**Comment by funlee** [comment]
> They work for me. What browser are you using?

I changed the demo just now

**Comment by alvarotrigo** [comment]
Try using the scrollOverflow option `click:false` as suggested [in this topic](https://github.com/alvarotrigo/fullPage.js/issues/3414) as well as in [this one](https://github.com/alvarotrigo/fullPage.js/issues/2047).

**Comment by funlee** [comment]
> Try using the scrollOverflow option `click:false` as suggested [in this topic](https://github.com/alvarotrigo/fullPage.js/issues/3414) as well as in [this one](https://github.com/alvarotrigo/fullPage.js/issues/2047).

thanks, I solutioned this problem

**Comment by alvarotrigo** [comment]
Awesome tot hear!
