### ISSUE TITLE
How to know which section got into view?

### ISSUE THREAD

**Issue by sumanthyedoti** [alvarotrigo/react-fullpage#184]
How to know which section got into view?

I want to change header color depending on if a section is dark or light.

`window.addEventListener('scroll', (e) => {})` seems not working

@alvarotrigo 
Please help

**Comment by sumanthyedoti** [comment]
Used the callback
```
onLeave={(origin, destination, direction) => {
    console.log(destination.index);
    //...
}}
```
Thanks

**Comment by alvarotrigo** [comment]
That's the way :) 
Or you can even use [fullPage.js state classes](https://github.com/alvarotrigo/fullPage.js#state-classes-added-by-fullpagejs) for that.
