### ISSUE TITLE
fullpage_api is not defined (only JS+JQuery)

### ISSUE THREAD

**Issue by nicooh** [alvarotrigo/react-fullpage#188]
I imported fullpage.js and fullpage.css and in my project I wanted to make a button that links to the next section. Below is the part of the code that doesn't work.

    $('#fullpage').fullpage({
		//options here
		autoScrolling:true,
		scrollHorizontally: true
	});

	$.fn.fullpage.setAllowScrolling(true);
    
    
    $(".mouse").click(function(){
        console.log("test");
        fullpage_api.moveSectionDown(); 
    });

thanks for the help

**Comment by alvarotrigo** [comment]
Are you using the react component? Or the plain JS version?

By the code you posted it seem you are not using react?

**Comment by nicooh** [comment]
Plain JS with Jquery

**Comment by alvarotrigo** [comment]
Then I would recommend you to check the [the fullpage.js documentation](https://github.com/alvarotrigo/fullPage.js) and check the [provided examples](https://github.com/alvarotrigo/fullPage.js/tree/master/examples),.
