### ISSUE TITLE
license

### ISSUE THREAD

**Issue by giusi77** [alvarotrigo/react-fullpage#189]
Hi, 
I just baught a fullPage license because fullPage is great and put the key into licenseKey: param but I still get a notifaction in the console. Is that normal or should the message dissapear?

ciao

**Comment by alvarotrigo** [comment]
Then it means you are not using it correctly :)

Make sure it looks like this:

`licenseKey: YOUR KEY HERE,`

You can use [fullpage.js inspector](https://alvarotrigo.com/fullPage/inspector/) to check errors in your page.
