### ISSUE TITLE
Propagate touch events on fixed positioned elements outside wrapper.

### ISSUE THREAD

**Issue by INMVMNI** [alvarotrigo/react-fullpage#190]
I found this issue posted in the fullpage.js repo and am looking for a react-fullpage solution to the same problem.

https://github.com/alvarotrigo/fullPage.js/issues/1912#issuecomment-199222246

I started my project using react-fullpage, but switched to fullpage.js so I could use the technique of changing $(WRAPPER_SEL) for $(document) in addTouchHandler and removeTouchHandler. 
This achieved the effect I was looking for, but now I’m running into errors indicating I’m initializing fullpage.js more than once.  The error is showing fullpage.js being initialised in parent components and React Router components like Route and Switch.  I haven’t been able to solve this and would rather just keep things simple and use react-fullpage.

Is there an equivalent method to changing $(WRAPPER_SEL) for $(document) that can be achieved in react-fullpage?

**Comment by alvarotrigo** [comment]
Unfortunately there's no solution for it on fullpage.js at the moment and therefore neither for any of its wrappers (react, angular and vue).

However, you can create your own custom wrapper :)
Just replace the fullpage.extensions.min.js file for the modified version of fullpage.js. You can do it here:
https://github.com/alvarotrigo/react-fullpage/blob/master/components/ReactFullpage/index.js#L54

Then just run the following to create the dist files:

```sh
npm run build
```
