### ISSUE TITLE
How to use parallax in react

### ISSUE THREAD

**Issue by lardi** [alvarotrigo/react-fullpage#191]
I tried example from [old issue](https://github.com/alvarotrigo/react-fullpage/issues/31#issuecomment-440237111) and it's seem not working.
Is there any other example to do Parallax?

**Comment by alvarotrigo** [comment]
Have you checked the example in the docs?
https://github.com/alvarotrigo/react-fullpage#examples

Or the one in the examples folder?
https://github.com/alvarotrigo/react-fullpage/blob/master/examples/react/src/index.js#L9

**Comment by lardi** [comment]
I meant parallax with image background like this [https://alvarotrigo.com/fullPage/extensions/parallax.html](https://alvarotrigo.com/fullPage/extensions/parallax.html)

**Comment by alvarotrigo** [comment]
Yeah I meant it too :)

**Comment by alvarotrigo** [comment]
First you'll have to purchase the extension, then import it as detailed in both links I gave you.
