### ISSUE TITLE
Browser back on to first section does not work

### ISSUE THREAD

**Issue by rburgst** [alvarotrigo/react-fullpage#203]
### Link to isolated reproduction with no external CSS / JS
https://alvarotrigo.com/react-fullpage/

### Steps to reproduce it
1. navigate to the page
2. scroll to section 2
3. browser back

#### Expected
Should go back to first section

#### Actual
Stuck at section 2

### Versions 
Firefox 79 (Mac OSX Catalina)

**Comment by alvarotrigo** [comment]
Thanks for reporting it!
It is actually a bug in the fullPage.js library itself not on the React Wrapper. 

Duplicated of https://github.com/alvarotrigo/fullPage.js/issues/950.

**Comment by rburgst** [comment]
I reported it specifically here because at least on https://alvarotrigo.com/fullPage/examples/scrollBar.html it seems to work fine.

**Comment by alvarotrigo** [comment]
It stills fails there :)
Going back will display a white page (if there wasn't any other when accessing that url)
