### ISSUE TITLE
gif images only work when I first switch, I want to know how can I solve it

### ISSUE THREAD

**Issue by free-leaves** [alvarotrigo/react-fullpage#204]
I copied the example and replaced the text with  gif images but the pictures will only have animation effect when switching for the first time. I want to know how I can solve this problem

**Comment by alvarotrigo** [comment]
> I want to know how I can solve this problem

This has nothing to do with fullPage.js but with GIF images.
You'd better ask about that in another place such as https://stackoverflow.com/ where they'll be able to help you better.
