### ISSUE TITLE
Normal scrolling on mobile devices

### ISSUE THREAD

**Issue by Happy-Child** [alvarotrigo/react-fullpage#208]
Hi

How can I use the plugin only on desktops, on mobile to do normal scrolling.
I don't really want to duplicate the markup and define it by condition.

Are all options available in the reagent version as in the regular version? https://github.com/alvarotrigo/fullPage.js

I can't find a suitable option for this behavior in the source code of the plugin for the react.

Thank.

**Comment by alvarotrigo** [comment]
> How can I use the plugin only on desktops, on mobile to do normal scrolling.

Just use the responsive options such as `responsiveWidtdh`, `responsiveHeight` or `fp-auto-height-responsive`.

You can even go further and use the [Responsive Slides extension](https://alvarotrigo.com/fullPage/extensions/responsive-slides.html) to turn horizontal slides into vertical sections. 

> Are all options available in the reagent version as in the regular version?

Yes. This is just a wrapper to simplify its use in React, fullPage.js still being the core library underneath it.

**Comment by Happy-Child** [comment]
Thank
