### ISSUE TITLE
Issues with trying to load scrollHorizontally extension

### ISSUE THREAD

**Issue by danielrvoigt** [alvarotrigo/react-fullpage#21]
When trying to load in the scrollHorizontally extension in my own environment (create-react-app) I am getting errors. However, I was able to successfully get the example repo up and running with the same extension. The errors I'm getting from my env are the following:

./src/fullpage.scrollHorizontally.min.js 
  Line 8:  'fp_utils' is not defined      no-undef 
  Line 8:  'fp_utils' is not defined      no-undef
  Line 8:  'fullpage_api' is not defined  no-undef
  Line 8:  'fullpage_api' is not defined  no-undef
  Line 8:  'fullpage_api' is not defined  no-undef

After looking at the lib more in depth, the variables that supposedly aren't defined in this instance are defined in the main fullpage.js dependency, so it seems like that isn't loading. I don't know why that would be the case.

I'm using the same code from index.js of the example repo and I've downloaded the necessary dependencies (@fullpage/react-fullpage)

For reference, my index.js:

```
import React from 'react';
import ReactDOM from 'react-dom';
import ReactFullpage from '@fullpage/react-fullpage';
import 'fullpage.js/vendors/scrolloverflow'; // Optional. When using scrollOverflow:true
import './fullpage.scrollHorizontally.min' // Optional. When using fullpage extensions


const fullpageOptions = {
  anchors: ['firstPage', 'secondPage', 'thirdPage'],
  sectionsColor: ['#282c34', '#ff5f45', '#0798ec'],
  callbacks: ['onLeave'],
  scrollOverflow: true,
  scrollHorizontally: true
};

const FullpageWrapper = fullpageProps => (
  <ReactFullpage
    {...fullpageProps}
    render={({ state, fullpageApi }) => {
      console.log('render prop change', state); // eslint-disable-line no-console

      return (
        <div id="fullpage-wrapper">
          <div className="section section1">
            <h3>Section 1</h3>
            <button onClick={() => fullpageApi.moveSectionDown()}>
              Move down
            </button>
          </div>
          <div className="section">
            <div className="slide">
              <h3>Slide 2.1</h3>
            </div>
            <div className="slide">
              <h3>Slide 2.2</h3>
            </div>
            <div className="slide">
              <h3>Slide 2.3</h3>
            </div>
          </div>
          <div className="section">
            <h3>Section 3</h3>
          </div>
        </div>
      );
    }}
  />
);

ReactDOM.render(
  <FullpageWrapper {...fullpageOptions} />,
  document.getElementById('react-root'),
);

export default FullpageWrapper;


```

**Comment by alvarotrigo** [comment]
> However, I was able to successfully get the example repo up and running with the same extension. 

Order matters:

```javascript
import ReactFullpage from '@fullpage/react-fullpage';
import 'fullpage.js/vendors/scrolloverflow'; // Optional. When using scrollOverflow:true
import './fullpage.scrollHorizontally.min' // Optional. When using fullpage extensions
``` 

Notice how the docs place them before including react-fullpage.js:
https://github.com/alvarotrigo/react-fullpage#examples

**Comment by danielrvoigt** [comment]
The problem still persists when ReactFullpage is imported first. Must have switched up the imports when debugging, but it doesn't solve the problem.

**Comment by danielrvoigt** [comment]
```
import 'fullpage.js/vendors/scrolloverflow'; // Optional. When using scrollOverflow:true
import './fullpage.scrollHorizontally.min' // Optional. When using fullpage extensions
import ReactFullpage from '@fullpage/react-fullpage';
```

I'm getting the same error with the extension scripts imported first. My code is the same as the example, just in a different env.

Error: 

./src/fullpage.scrollHorizontally.min.js
Line 8: 'fp_utils' is not defined no-undef
Line 8: 'fp_utils' is not defined no-undef
Line 8: 'fullpage_api' is not defined no-undef
Line 8: 'fullpage_api' is not defined no-undef
Line 8: 'fullpage_api' is not defined no-undef
