### ISSUE TITLE
adding `normalScrollElements` option leads to `Cannot read property '0' of null`

### ISSUE THREAD

**Issue by switchnollie** [alvarotrigo/react-fullpage#210]
### Description

Fullpage.js crashes when I add the `normalScrollElements` option with a class selector to an element that is rendered inside a child section.

### Link to isolated reproduction with no external CSS / JS

[Link to CodeSandbox](https://codesandbox.io/s/react-fullpage-bug-normalscrollelements-z0c5h?file=/src/App.js)

### Steps to reproduce it
1. Add `normalScrollElements` option and a corresponding element with the specified className (`SCROLLABLE_CONTENT_SEL` in the provided example)
2. Scroll to the section with the normalScrollElement
3. App crashes with the following error

```
Uncaught TypeError: Cannot read property '0' of null
    at Object.setIscroll (react-fullpage.js:1106)
    at HTMLDocument.Ee (react-fullpage.js:1122)
```

### Versions 
Chrome 85.0.4183.121, MacOS 10.15.3

**Comment by alvarotrigo** [comment]
I've updated the react-fullpage module to include the latest fullpage.js version 3.0.9.
Can you please install version 0.1.18 of @fullpage/react-fullpage and try again?

**Comment by switchnollie** [comment]
Seems to fix the issue, thank you for the quick support!

**Comment by alvarotrigo** [comment]
Glad you managed to fix it! 😉
