### ISSUE TITLE
Fullpage JS affected by offset element outside of fullpage-wrapper with `responsiveWidth`

### ISSUE THREAD

**Issue by rockmanvnx6** [alvarotrigo/react-fullpage#219]
### Description

Full-page JS wrapper height is changed by another element which offset out of the screen when **switching from mobile view to desktop view with `responsiveWidth`.**

![image](https://user-images.githubusercontent.com/16440123/102033724-40a6bc80-3e10-11eb-8a0f-e0db7b410a2a.png)

The "scroll-down" element is offset by 250px when exiting from mobile view with `responsiveWidth=767`

### Link to isolated reproduction with no external CSS / JS
[codesandbox](https://codesandbox.io/s/gatsby-fullpage-forked-umvnr?file=/src/pages/page-2.js)

The **bug only happens when scrolling under section 1 when the offset happens**. I do use `animejs` to replicate the translateY only.

### Steps to reproduce it
1. Maximise window, **scroll to Section 2 or 3**. The `scroll-down` bar should disappear, this is the expected behavior.
2. Minimise window (window width < responsiveWidth), **keep the scroll within section 2 or 3**
3. Maximise window, section 2 or 3 will have white space with height = 250px. 

### Versions 
Browser: chrome 86.0
OS: All OS
Device: PC

**Comment by alvarotrigo** [comment]
There can not be anything outside fullPage.js wrapper that is not fixed positioned. 
This one is the problem:

![image](https://user-images.githubusercontent.com/1706326/102063030-cc5f1f80-3df5-11eb-8c70-90f774c4ffb4.png)
