### ISSUE TITLE
Provide an example on how to use callbacks.

### ISSUE THREAD

**Issue by anshuraj** [alvarotrigo/react-fullpage#22]
Please provide an example how to use callbacks using the react wrapper. The documentation does not help at all. I could see the callback array in state but how do I call the callback function?

**Comment by alvarotrigo** [comment]
Good point! Thanks for reporting it! 
We'll have to add a better example of it in the docs.

Right now you can use them making use of the `state` variable:


```javascript
 render={({ state, fullpageApi }) => {
      console.log("render prop change", state); // eslint-disable-line no-console

      if (state.callback === "onLeave") {
        if (state.direction === "down") {
          console.log("going down..." + state.origin.index);
        }
      }
      ....
```

I've updated the [CodeSandbox example](https://codesandbox.io/s/m34yq5q0qx) with it.

However I'll see if we can improve it in the future.

**Comment by cmswalker** [comment]
@anshuraj I believe this will fix your issue https://github.com/alvarotrigo/react-fullpage/pull/23

This will make it easier to build callbacks within your component and pass them down to fullpage
