### ISSUE TITLE
TypeError: Cannot read property '0' of null & Cannot read property 'destroy' of undefined

### ISSUE THREAD

**Issue by mathisang** [alvarotrigo/react-fullpage#220]
Hi !

I'm trying to fetch an API to have X number of section.
With react-fullpage I have 2 errors : 
TypeError: Cannot read property '0' of null & TypeError: Cannot read property 'destroy' of undefined

Example : https://codesandbox.io/s/silly-bash-j5g94?file=/src/App.js

On my local, when I save modifications I can see my API results. But if I refresh : errors.

Thanks !

**Comment by alvarotrigo** [comment]
Try adding a dummy section before you get the content.
fullPage.js needs sections in order to function and expect them in the DOM when fullpage.js is initialised. 

You can then remove that dummy section when you create the ones you need on your loop.

**Comment by mathisang** [comment]
It's working !

Thank you for help.

**Comment by alvarotrigo** [comment]
Glad it did!! :)
