### ISSUE TITLE
Receiving 2 Errors: "TypeError: Cannot read property 'parentNode' of undefined" & "TypeError: Cannot read property 'destroy' of undefined"

### ISSUE THREAD

**Issue by tylerhuyser** [alvarotrigo/react-fullpage#221]
My repo can be found [here](https://github.com/tylerhuyser/tyler_huyser_portfolio).

I installed using the NPM command listed in the repo. I import FullPage.js in the FullPageWrapper component, which is referenced within the App.js component.

**Comment by tylerhuyser** [comment]
Resolved! I did not realize that I had to name my section with the className="section"

**Comment by alvarotrigo** [comment]
Glad to know you managed to solve it! :)
