### ISSUE TITLE
Parallax scrolling stops working on cached copy of site (with backgrounds displaced)

### ISSUE THREAD

**Issue by Contengo** [alvarotrigo/react-fullpage#225]
We are using react-fullPage on our new next.js - based website [contengo.net](https://contengo.net) with parallax scrolling. It generally works very well, but it is exhibiting an intermittent fault which appears to be tied to the way Google Chrome is caching the site.

The way to reproduce this is as follows:

1. Visit the site using the link above with Google Chrome.
2. Scroll down through some of the sections.
3. Now close the browser and wait for some time (I haven't been able to determine how long - try an hour or so).
4. Now open Chrome and type in Contengo.net - selecting the cached version from the suggestions.
5. When the site has loaded scroll down to any slide beneath the home page.

This will sometimes show the problem, sometimes not. The attached screenshots show the problem (and the normal state), and also show the Chrome Devtools view of the backdrop element in both cases.  The problem seems to exhibit more readily on an Android phone with Chrome than on a PC - but it occurs on both. It's not clear whether it happens with other browsers.

When the problem is manifesting there is a permanent displacement of the background - in the Y direction for slide 0 of each section and the X direction for all the other slides. Also when you slide around you can see that the fullpage effect is working still, but the parallax scrolling is not doing anything (which is presumably why the backgrounds are stuck out of position). 

I tried adding some javascript to detect the condition and reset the sliders as a one-off action - that works in terms of not having a displaced background - but the parallax scrolling is still not working in that situation.

In a nutshell, it looks like the normal fullPage.js javascript is running in that situation, but the parallax scrolling bit has died. 

I have not managed to reproduce this in a local development environment - I think it only happens with the production-rendered, browser-cached copy of the site. 

Can you help with a fix or a workaround?

**Problem showing:**
![Problem showing](https://user-images.githubusercontent.com/68324123/105772738-8cde3400-5f5a-11eb-8e14-cc5122f201ef.jpg)

**Problem showing - devtools view:**
![Problem - devtools view](https://user-images.githubusercontent.com/68324123/105772747-9071bb00-5f5a-11eb-9c7b-7942b64694e9.jpg)

**Normal (no problem):**
![No problem](https://user-images.githubusercontent.com/68324123/105772763-95cf0580-5f5a-11eb-8032-9d37e4d0a52c.jpg)

**Normal - devtools view:**
![No problem - devtools view](https://user-images.githubusercontent.com/68324123/105772767-98315f80-5f5a-11eb-992f-56991f518619.jpg)

**Comment by Contengo** [comment]
It appears that the latest releases of Google Chrome have resolved this problem - I did report it so maybe they acted on that.

**Comment by alvarotrigo** [comment]
Awesome! Glad to know you managed to fix your issue! 👍
