### ISSUE TITLE
Installed NPM Package Size Too Big Because It Includes Examples Folder

### ISSUE THREAD

**Issue by ram-a-dhan** [alvarotrigo/react-fullpage#229]
### Description
The installed NPM package includes examples folder hence the node_modules gains unnecessary 36.8MB of data. 

### Image Evidence
![Screenshot from 2021-02-19 14-38-08](https://user-images.githubusercontent.com/58775678/108473534-bae83700-72c0-11eb-8df0-cf04ef0b56d1.png) 
![Screenshot from 2021-02-19 14-38-18](https://user-images.githubusercontent.com/58775678/108473544-bde32780-72c0-11eb-9746-ca4b19d815bb.png) 

### Steps to reproduce it
1. Install the package using `npm i @fullpage/react-fullpage`. 
2. Wait for it to finish installing. 
3. Look inside `node_modules/@fullpage/react-fullpage` folder and see the properties of `examples` folder. 

### Versions 
```
"@fullpage/react-fullpage": "^0.1.19"
```

---

I know its easy to just delete `examples` from `node_modules` but may i suggest to add an `.npmignore` file and add the `examples/` folder to de-bloat the package. 

Thank you.

**Comment by alvarotrigo** [comment]
> I know its easy to just delete `examples` from `node_modules` but may i suggest to add an `.npmignore` file and add the `examples/` folder to de-bloat the package.

Sure! Thanks for the feedback! Didn't even notice! 👍 

Want to do the pull request yourself?
If not, let me know and I'll add the ignore file :)

**Comment by ram-a-dhan** [comment]
>Want to do the pull request yourself?

Sure! Why not.

**Comment by ram-a-dhan** [comment]
Do i need to be a contributor first and make a new branch or just make the new file directly on the remote master branch?

**Comment by alvarotrigo** [comment]
You will automatically become a contributor when you create your first pull request and it gets merged.
So you can just commit your changes to the DEV branch to create your pull request and I'll review them.

**Comment by alvarotrigo** [comment]
Fixed one dev thankst to @ram-a-dhan 👍

**Comment by ram-a-dhan** [comment]
And thank you for making this awesome package.

**Comment by alvarotrigo** [comment]
Let's keep it open until I merge it.

**Comment by ram-a-dhan** [comment]
Oh okay. 
I'm really new to this so please forgive me.

**Comment by alvarotrigo** [comment]
Fixed in version 0.1.22
