### ISSUE TITLE
Override Scrolling Effect

### ISSUE THREAD

**Issue by herbievine** [alvarotrigo/react-fullpage#230]
Is there a way to add a Navigation component inside ReactFullPage, so it has access to `fullpageApi` without it being affected by the scroll effect?

```
import ...

function App() {
    return (
        <div className="">
            <FullPageScrollingEffect
                scrollOverflow={true}
                scrollingSpeed = {800}
                render={({ fullpageApi }) => {
                    return (
                        <div>
                            <div className="fixed right-1.5 z-50">   // } Have these not affected
                                <Navigation api={fullpageApi} />     // } by the effect but have
                            </div>                                   // } access to the API
                            <Landing api={fullpageApi} />
                            <Biography api={fullpageApi} />
                            <Skills api={fullpageApi} />
                            <Socials api={fullpageApi} />
                        </div>
                    )
                }}
            />
        </div>
    )
}

export default App
```

**Comment by alvarotrigo** [comment]
You can always access the window global object in any case `fullpage_api`.

**Comment by herbievine** [comment]
> You can always access the window global object in any case `fullpage_api`.

Oh nice I had no idea it was accessible globally 😁. Thanks 👍

**Comment by alvarotrigo** [comment]
No problem! Glad you managed to fix your issue! :)

**Comment by herbievine** [comment]
I seem to have yet another issue however when I get the API from the window object. When I try to access `fullpage_api.getActiveSection()`, I get an error... However, if I do the same thing but with the API passed as a prop (as seen here: `<Landing api={fullpageApi} />`), it works fine. So is there any way around this?

**Comment by herbievine** [comment]
You can check the full code here: https://github.com/herbievine/herbievine.com

**Comment by alvarotrigo** [comment]
Try running `window.fullpage_api.getActiveSection()` that on the JS console.
You might be calling it before fullpage gets initialised.
