### ISSUE TITLE
navigationTooltips doesn't update with setState if the new tooltips length is the same of the previous

### ISSUE THREAD

**Issue by sehnryr** [alvarotrigo/react-fullpage#242]
### Description
The navigationTooltips doesn't update if the new tooltips array length is the same of the previous.

### Link to isolated reproduction with no external CSS / JS
Here's a reproduction : https://codesandbox.io/s/4kkc4

### Steps to reproduce it
1. Go to the above link or [here](https://codesandbox.io/s/4kkc4)
2. Click on the "click here to update titles" button

Espected behaviour : The navigationTooltips updates and show the updated tooltips

Observed behaviour : The navigationTooltips keeps the previous tooltips

### Versions 
Firefox Nightly `90.0a1 (2021-05-01) (64 bits)`
@fullpage/react-fullpage `0.1.19`
react `16.9.0`

**Comment by alvarotrigo** [comment]
Thanks for reporting it!

Currently fullPage.js doesn't have a way to force the dynamic update of tooltips, so it would have to get destroyed and initilaised again.

I'll look into this tomorrow!
Should be an easy fix!

**Comment by alvarotrigo** [comment]
Ok, this should be fixed on the dev branch now.
You can try it using the dev branch files:
https://github.com/alvarotrigo/react-fullpage/blob/dev/dist/react-fullpage-umd.js

**Comment by alvarotrigo** [comment]
I'll keep this open until merged :)

**Comment by sehnryr** [comment]
Okay, thanks by the way :)
