### ISSUE TITLE
Dynamically adding section kicks you to the top for the page

### ISSUE THREAD

**Issue by teamtechalpha** [alvarotrigo/react-fullpage#253]
### Description
When I try to add a new section it takes us to the first section and then scrolls back to the active section.

### Link to isolated reproduction with no external CSS / JS
Please check the codesandbox link below:

https://codesandbox.io/s/dazzling-kepler-mi16c

### Steps to reproduce it
1. Scroll to a section other than the first one
2. Click on Add Section button at the top
3. It will take you to page 1 and then scroll back to the active section.

**Comment by alvarotrigo** [comment]
Use the fullpage.js option `animateAnchor={false}`.
That should fix the issue.

However, it will also turn off animations to the section/slide on page load. So for example if you access directly to an anchor using the URL (https://alvarotrigo.com/fullPage/#page2) you won't get the animation.

One thing you can do is change the option dynamically and just turn it off just before adding sections.
You can try perhaps doing something like this:


````
addSection = function(){
     fullpage_api.getFullpageData().options.animateAnchor = false;
     
     // add section here...
     ...
     
     fullpage_api.getFullpageData().options.animateAnchor = true;
}
```

**Comment by teamtechalpha** [comment]
I tried above mentioned solutions but none of them worked. 
Open the same codesandbox link ([https://codesandbox.io/s/dazzling-kepler-mi16c]) to see `animateAnchor` flag.

**Comment by alvarotrigo** [comment]
Yeah, I see it fails sometimes. Interesting... ok, I'll mark it as bug and hopefully we can fix it for future releases.

**Comment by Gibbo3771** [comment]
Hey I just discovered this library and I am looking to use it. Is this bug due to be fixed or is it low priority?

It's pretty much stopping me in my tracks since my sections are dynamic depending on user input.

**Comment by alvarotrigo** [comment]
It's due to be fixed, but there's no date yet.
However the whole code is open sourced so feel free to provide a fix if you find it :)

It seems to be working fine on the Vue wrapper:
https://codepen.io/alvarotrigo/pen/zpQmwq

https://github.com/alvarotrigo/vue-fullpage.js/blob/master/src/FullPage.vue#L17

**Comment by alvarotrigo** [comment]
> Hey I just discovered this library and I am looking to use it. Is this bug due to be fixed or is it low priority?

Ok, you are in your lucky day!
I've fixed it on the dev branch! 

Here you can see how to npm install a specific branch:
https://stackoverflow.com/a/39732501/1081396

**Comment by Gibbo3771** [comment]
> > Hey I just discovered this library and I am looking to use it. Is this bug due to be fixed or is it low priority?
> 
> Ok, you are on your lucky day!
> I've fixed it on the dev branch!
> 
> Here you can see how to npm install a specific branch:
> https://stackoverflow.com/a/39732501/1081396

You my friend are stunning!

> However the whole code is open sourced so feel free to provide a fix if you find it :)

I appreciate this, I was just hoping to pay for it and get it working out the box lol. I'm not the one fronting the cash haha.

**Comment by alvarotrigo** [comment]
Fixed in the latest release.
