### ISSUE TITLE
the last section becomes active when scrolling up in the first section

### ISSUE THREAD

**Issue by mjavadHasanzade** [alvarotrigo/react-fullpage#260]
I'm using Fullpage.js in a next-js application.
in the mobile version when the first section is active and I scroll the page up, the last section (footer) become active (page jumps to footer) and I have no error for "Fullpage.js can only be initialized once" according to # 2237 issue

**Comment by alvarotrigo** [comment]
If you are using the [official React component for fullpage.js](https://alvarotrigo.com/react-fullpage/) make sure to check the react example?
https://github.com/alvarotrigo/react-fullpage/tree/master/examples/next

**Comment by mjavadHasanzade** [comment]
this problem was because of next-js default styles
