### ISSUE TITLE
Dynamic navigation prop - changing navigation prop does not update fullpage

### ISSUE THREAD

**Issue by vaultec81** [alvarotrigo/react-fullpage#267]
### Description
The navigation prop (and I am sure others) do not update the fullpage.js state when updated in react.

### Link to isolated reproduction with no external CSS / JS
https://codesandbox.io/s/react-fullpage-js-example-forked-yqxct?file=/src/index.js

### Steps to reproduce it
1. Setup a react project using full page JS react component
2. Set an initial value for `navigation` 
3. Proceed to modify the value for navigation
4. Witness the navigation bar never being updated according to the modified value

### Versions 
v0.1.19

I am sure this is the case elsewhere across the codebase. It would be great to have the react props dynamically update the underlying fullpage.js state, or provide instructions on how to update the fullpage.js state with some other method.

**Comment by alvarotrigo** [comment]
The issue should be fixed on the dev branch.

Here you can see how to npm install a specific branch:
https://stackoverflow.com/a/39732501/1081396

**Comment by alvarotrigo** [comment]
Fixed in version 0.1.22
