### ISSUE TITLE
update some parts of a section 

### ISSUE THREAD

**Issue by mjavadHasanzade** [alvarotrigo/react-fullpage#272]
Hi!
I'm using full-page in a Next JS application and I just need to update some parts of a section ( a full-page section) not all of the section, by scrolling down or up ( I need hash-change too) please help me if this feature is possible

**Comment by alvarotrigo** [comment]
Unfortunately, we only provide support for fulpage.js questions of usage and the react wrapper for it, but we do not provide consulting services here :)
