### ISSUE TITLE
Triggering GreenSock animations when a slide is active

### ISSUE THREAD

**Issue by chrish-d** [alvarotrigo/react-fullpage#275]
Hi there,

I originally posted this on the GreenSock forums, but they suggested I asked here. I believe I'm a bit stuck in the middle between two products, as the question involves both platforms. I'm hoping by asking here I can stitch together answers from both places to form a solution :)

**Here's my problem:**

I'm trying to add some animations to my fullPage.js slides. I have a series of slide components, and the desired effect is to trigger a set of animations once the slide is active.

From doing some reading, I believe timelines are the best way to handle this, so I'm passing a timeline object to the component and doing the animating from within.

The problem is that all of the slides animate as soon as the app loads.

 Here's a simple recreation of what I'm trying to do, showing pretty much the same code as my real app and having the same undesired effects:

https://codesandbox.io/s/priceless-meitner-17759

**Comment by alvarotrigo** [comment]
You probably have to make use of [fullPage.js callbacks](https://github.com/alvarotrigo/fullPage.js#callbacks) for that. 
See a demo online here:
https://codepen.io/alvarotrigo/pen/XbPNQv

Just trigger the animation based on the conditions you need inside the callback.

**Comment by chrish-d** [comment]
Hey @alvarotrigo, thanks for the fast reply. I didn't get back to you sooner because I thought this information would be enough to go on, but I'm still a bit stuck. I feel like I essentially need to pass a `prop` to the active slide to say "this is active now", and then in a `useEffect` callback or something, animate the slide if that `prop` is `true`... but I can't figure this out using the callbacks.

Any suggestions? :-)

**Comment by alvarotrigo** [comment]
That seems to be more of a React question than a fullPage.js one.
Try asking in other places like stackoverflow.com. This should be a common problem in other scenarios and when using many other JS libraries with callbacks.

**Comment by chrish-d** [comment]
No problem, I'll redirect my question there. Thanks :)

**Comment by alvarotrigo** [comment]
You probably just need to set up a variable.
Something like this:

```
//on full-page initialisation
afterLoad={afterLoad}


// on your hooks
let loadedSection;
const afterLoad = (origin, destination, direction) => {
      loadedSection = destination;
},


useEffect(() => {
    console.log(loadedSection)
  });
```
