### ISSUE TITLE
Video auto play not working 

### ISSUE THREAD

**Issue by Deepakajjan** [alvarotrigo/react-fullpage#279]
Video auto play not working when we go to one section and scroll back to the top.

https://locationl.q.starberry.com/marketing/

1. Open this page, you can see the video play on the first instance
2. Scroll below and scroll back to the top again, as you can see the video does not play by default, we have added the autoplay at the code level for some reason it is not playing.
3. We have to reload the page again in order for the video to play which is not great user experience.

### Versions 
All browsers, all versions

It will be really helpful if you could review this at your earlier convenience and get back with a solution.

Thanks

**Comment by alvarotrigo** [comment]
Nothing to worry about!
See the [docs regarding auto play/pause](https://github.com/alvarotrigo/fullPage.js#auto-playpause-embedded-media) and apply those changes :)
