### ISSUE TITLE
Using setState() with react-fullpage

### ISSUE THREAD

**Issue by rogerdegers** [alvarotrigo/react-fullpage#29]
Hi, I am having trouble using setState() as it re-render my whole fullpage and send me back to section 1:

```jsx
class Home extends React.Component {
    constructor(props) {
        super(props);
        this.state = {
            addClass: "blabla"
        }
    }
    render() {
        const fullpageOptions = {
            scrollingSpeed: 1200,
            responsiveWidth: 992,
            responsiveHeight: 600,
            onLeave: (destination) => {

                console.log(this.state.addClass)

                if (destination.index == 1) {
                    this.setState({addClass: "animated fadeIn"}, () => {
                        console.log(this.state.addClass);
                })}
            }
        };
        const FullpageWrapper = (fullpageProps) => (

            <ReactFullpage
                {...fullpageProps}
                render={() => {
                    return (
                        <div id="fullpage-wrapper">
                           ....
                        </div>
                    );
                }}
            />
        );



        return (
            <FullpageWrapper {...fullpageOptions} />
        )
    }
}


export default Home;
```

**Comment by cmswalker** [comment]
This could be due to the page location while using hot reloading in dev. Will double check, have you reproduced it in production or just dev? This is certainly a dev env annoyance I've come across

**Comment by cmswalker** [comment]
@jwongbandue @rogerdegers I updated your examples to reflect syntax highlighting. Have you observed this in production or dev only?

**Comment by rogerdegers** [comment]
Thanks for the update @cmswalker , Experienced just in dev. 

I think it is due to the re-render of the object fullpage when setState() is called.

**Comment by cmswalker** [comment]
yeah its a hot-reloading issue in dev only. Even when I was maintaining https://github.com/cmswalker/fullpage-react it affected that in dev as well. I'll look into to see if I can get it to persist but I can't guarantee it. Just to be clear to those coming across this issue, it affects development only and causes the page to reset to the top on save.

**Comment by cmswalker** [comment]
I'm seeing other issues come up that may look like more serious bugs but are in fact just issues w/ hot reload. In development it might make sense for react-fullpage to render a button/toolbar that allows manual resetting of the fullpage state.
