### ISSUE TITLE
Why does FullPage JS use Display: Table on default and not Display: Flex

### ISSUE THREAD

**Issue by Sorumeiji** [alvarotrigo/react-fullpage#299]
Hey Alvarotrigo,

I was wondering why you don't use display: flex and each section is using display: table. This causes each section to display like table elements instead of adjusting like in flexbox or grid. When you back and forth, the section, sometimes, will move off the page in overflow on re-rendering.  When I set the parent of the wrapper to display: flex it doesn't do this at all.

Also, I was wondering if I could override  fp-tableCell, fp-section fp-table in my css?

**Comment by alvarotrigo** [comment]
> I was wondering why you don't use display: flex and each section is using display: table.

Basically because `display: flex` wasn't even a thing supported by most browsers whent fullPage.js was born :)

fullPage.js 4 is about to be released too and the `display: table` will get dropped too.  

> Also, I was wondering if I could override fp-tableCell, fp-section fp-table in my CSS?

Sure!
