### ISSUE TITLE
Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.

### ISSUE THREAD

**Issue by guhyeon** [alvarotrigo/react-fullpage#300]
### Description
nextjs sample does not working.
with message
Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.

![image](https://user-images.githubusercontent.com/9765614/156990857-d3289777-9884-4dd0-9213-5c3ed3850bf8.png)

### Link to isolated reproduction with no external CSS / JS
[Ideally in [codesandbox.io](https://codesandbox.io/s/m34yq5q0qx), links to personal websites won't be reviewed unless isolated. Reported issues without a reproduction might get closed.]

### Steps to reproduce it
1. clone this project
2. cd example/nextjs
3. yarn install
4. yarn dev

### Versions 
[Browser, operating system, device, ...]

**Comment by jerehut** [comment]
You should try the version 0.1.19, I got the same error and even the official CodeSandBox environment gets it: https://codesandbox.io/s/m34yq5q0qx

Downgrading fixed it for me!

Hey @alvarotrigo, are you sure the latest versions are ready for publishing?

**Comment by alvarotrigo** [comment]
@jerehut I'm aware of the issue. I'm trying to figure out what happened. 
Any help will be appreciated :)

**Comment by alvarotrigo** [comment]
Should be fixed on the dev branch thanks to this pull request:
https://github.com/alvarotrigo/react-fullpage/pull/301

**Comment by alvarotrigo** [comment]
This should be fixed now in version 0.1.22

**Comment by joelstein** [comment]
I was having this same issue with SSR.

This change in vite.config.js fixed it for me for some reason:

```js
ssr: {
  noExternal: ["@fullpage/react-fullpage"],
},
```

**Comment by alvarotrigo** [comment]
> I was having this same issue with SSR.

Interesting...  With the latest version I assume?

**Comment by joelstein** [comment]
Yep.
