### ISSUE TITLE
[Breaking change] Typescript types error 0.1.22

### ISSUE THREAD

**Issue by tonytoth** [alvarotrigo/react-fullpage#304]
### Steps to reproduce it

`"@fullpage/react-fullpage": "^0.1.22"` has 2 mandatory fields which I am not sure they should be:
 - `cards` 
 - `cardsOptions`

If you have a look at declaration file:

`interface FullPageProps extends fullpageOptions {}`

`
export interface fullpageOptions {
    cards: boolean;
    cardsOptions: CardsOptions;
}
`

**Comment by alvarotrigo** [comment]
Thanks for reporting it!! 👍 
Fixed on the dev branch!

**Comment by nashfisher** [comment]
Any  idea when this update will be released?

**Comment by alvarotrigo** [comment]
There's a major version change in fullpage.js that has been released yesterday.
Version 4.

There are still some issues so I'll wait until I extinct the main fires to merge it on react-fullpage.js too.

**Comment by alvarotrigo** [comment]
Fixed in 0.1.25! 🎉
