### ISSUE TITLE
Cannot read properties of undefined (reading 'call')

### ISSUE THREAD

**Issue by braco** [alvarotrigo/react-fullpage#305]
Trying to include this package in a CRA app with

`import ReactFullpage from '@fullpage/react-fullpage';`

yields 

`Cannot read properties of undefined (reading 'call')`

from 

`at Object.../node_modules/@fullpage/react-fullpage/dist/react-fullpage.js`

versions

`"@fullpage/react-fullpage": "^0.1.22",`
`"react-scripts": "^4.0.3",`

Any ideas?

**Comment by braco** [comment]
Sorry, didn't see dupe!

https://github.com/alvarotrigo/react-fullpage/issues/303

**Comment by alvarotrigo** [comment]
Any help will be appreciated! ;)
