### ISSUE TITLE
fp-scrollable being removed due to window.fullpage_api.reBuild();

### ISSUE THREAD

**Issue by NoahThomlison** [alvarotrigo/react-fullpage#311]
I have a page with 3 sections. The third section contains content that is dynamically rendered. I am using a filter button click function to change the state on this page and update my list. Within this function, I am calling window.fullpage_api.reBuild(); to dynamically resize the page. 

window.fullpage_api.reBuild(); is resizing the page however there are issues with it not consistently adding the fp-scrollable sections to the content. The behaviour is very confusing. 

On page load, the content is long and scrollable. If I filter to a short section the page resizes and the scroll goes away (the desired effect). If I then filter back to a long section the fp-scrollable tags are not readded and the section styling is wrong and not scrollable. If then re-filter to the same long section the fp-scrollable tags are readded.

**Comment by alvarotrigo** [comment]
Can you provide an isolated reproduction in [Codesandbox](https://codesandbox.io/s/m34yq5q0qx) with no CSS or JS files external to fullPage.js and the minimum amount of HTML code? Use empty sections unless strictly necessary for the reproduction.

**Comment by alvarotrigo** [comment]
Make sure to call the reBuild function right after the new content is added to the DOM. Not before.

**Comment by NoahThomlison** [comment]
@alvarotrigo I have tried to create an empty codesandbox using the react template but am having issues. I will try again. I am currently calling the reBuild function directly after the content has been updated. Please see below. It somewhat seems full page is behind a button click. If I do the following pattern 

Long amount of content initially with scrollable => click button to short section, scrollable off which is desired effect, => long section, scrollable is off and css gets messed with. If I re-click then at this point on the same filter scrollable and css returns.

It will take me some time to do the codesandbox but I can post a link to my page if you would like to see live the effect I am seeing. 

Button click function below:

  function buttonClick(e, stack){
    e.stopPropagation() 
    setFilter(stack)      
    setExpanded(!expanded)
    window.fullpage_api.reBuild();
  }

**Comment by alvarotrigo** [comment]
Your code should be fine assuming `setExpanded ` adds content synchronously.
If it makes an async request or has some timeouts or animations, then the reBuild has to be called after those async operations are done.

> It will take me some time to do the codesandbox but I can post a link to my page if you would like to see live the effect I am seeing.

We don't check specific websites unless you acquired the Business license.
But you can modify [this codesandbox](https://codesandbox.io/s/m34yq5q0qx) and adapt it to your needs.

**Comment by alvarotrigo** [comment]
Have you saved the changes? I can't see anything on the codesandbox
![image](https://user-images.githubusercontent.com/1706326/161570457-b0ff0bee-5eb0-4146-b4c6-295aa69f4566.png)

**Comment by NoahThomlison** [comment]
@alvarotrigo My mistake, saved now.

**Comment by alvarotrigo** [comment]
Yeah, this is related to the way React updates the DOM.
It won't do it synchronously when updating the state.

A simple hack is to use the `setTimeout` function to make sure the DOM is updated before calling rebuild:

```js
    setTimeout(function(){
      window.fullpage_api.reBuild();
    });
```

If you want to go for a more elegant way, check out if React provides any events/callbacks when the DOM finishes updating after modifying the state. 
Then call the `reBuild` method.

You can read more bout this issue here:
https://macarthur.me/posts/when-dom-updates-appear-to-be-asynchronous

**Comment by NoahThomlison** [comment]
@alvarotrigo Thank you for the help. I have used a useEffect to trigger when the state is updated and call the reBuild method. Really appreciate the help.
