### ISSUE TITLE
Question: Full Page React is still using the 3.12 depandenacy.

### ISSUE THREAD

**Issue by Sorumeiji** [alvarotrigo/react-fullpage#314]
Hello @alvarotrigo,

I seen Fullpage JS has been updated to version 4.05. Is there a release coming to update the dependacy and require for react as well?

**Comment by alvarotrigo** [comment]
Yeap!
It will take at least 2 weeks.

There are a few issues regarding licenses and extensions that we need to fix before moving forward.

**Comment by Sorumeiji** [comment]
@alvarotrigo thank for the response. I seen the release, and was excited for the changes I seen in the patch notes. I'll be sure to plan ahead then when that  get publish

**Comment by alvarotrigo** [comment]
@Sorumeiji awesome! ;)
