### ISSUE TITLE
The "Enable scrollbar causes flickering" bug has not been fixed

### ISSUE THREAD

**Issue by meisken** [alvarotrigo/react-fullpage#316]
The bug https://github.com/alvarotrigo/fullPage.js/issues/4345 is still there after I updated the version to 0.1.23

https://user-images.githubusercontent.com/38470704/164309126-38327af0-2352-497e-bd51-08225272a3fa.mp4

Reproduction code: https://codesandbox.io/s/react-fullpage-js-example-forked-ylxyp2?file=/src/index.js

**Comment by alvarotrigo** [comment]
> The bug [alvarotrigo/fullPage.js#4345](https://github.com/alvarotrigo/fullPage.js/issues/4345) is still there after I updated the version to 0.1.23

Yeah, that makes sense as 0.1.23 won't integrate fullPage.js version 4 yet.
It should be ready in a week or two.

**Comment by alvarotrigo** [comment]
Fixed in 0.1.25! 🎉
