### ISSUE TITLE
Is there any way to pass the MAIN_SELECTOR by customization, to cover the default value "fullpage"

### ISSUE THREAD

**Issue by MapleShaw** [alvarotrigo/react-fullpage#318]
### Description

![image](https://user-images.githubusercontent.com/1726349/164955521-d170c39d-d5d4-4921-9b8e-4dc46cc37ef2.png)
I use two DIV to handle the responsive between desktop and mobile, so there are two <ReactFullpage /> in different components, but in the same page.

It will cause the error "Fullpage.js can only be initialized once and you are doing it multiple times!"

Is there any way to pass the MAIN_SELECTOR by customization, to cover the default value "fullpage".

**Comment by alvarotrigo** [comment]
Change the IDs so you only initialize it once.
Use different initializations for mobile than for desktop.

Something like:

```js

if(inDesktop){
   new fullpage('#fullpage-desktop', {...});
}
else{
      new fullpage('#fullpage-mobile', {...});
}
```

**Comment by MapleShaw** [comment]
@alvarotrigo appreciate for reply, in that way, does it means I can not initialize in this way?
![image](https://user-images.githubusercontent.com/1726349/165460241-c7e9f956-6054-41ae-a928-6fd96bb37bd1.png)

**Comment by alvarotrigo** [comment]
You have to make sure to only initialize one instance of fullPage.js.
And at the moment you are initializing two as both have the same ID.

**Comment by MapleShaw** [comment]
Got it, thanks so much!
