### ISSUE TITLE
Can't build example file

### ISSUE THREAD

**Issue by alvarotrigo** [alvarotrigo/react-fullpage#32]
After doing on `npm install` on the root and on the `examples` folder.
Then trying to build the example with `npm run build`. I get the following error regarding the inclusion of the CSS file in the react component:

> ERROR in ../node_modules/fullpage.js/dist/fullpage.min.css 10:3
Module parse failed: Unexpected token (10:3)
You may need an appropriate loader to handle this file type.

![screen shot 2018-09-21 at 13 02 00](https://user-images.githubusercontent.com/1706326/45877564-952c7000-bd9e-11e8-8f66-c9fe136dbc95.png)

I believe previously, we were not adding the CSS in the component?
The `example/index.html` file still having the inclusion of the css file:

```html
    <link rel="stylesheet" type="text/css" href="https://unpkg.com/fullpage.js@3.0.1/dist/fullpage.min.css">
```

**Comment by alvarotrigo** [comment]
I guess there's no problem on removing the following line from `components/React-fullpage/index.js` ?:

```javascript
import fullpageStyles from 'fullpage.js/dist/fullpage.min.css'; // eslint-disable-line no-unused-vars
``` 

As long as they include it in their .html file?

**Comment by cmswalker** [comment]
somehow the stylesheet was removed. It's on the component itself to bundle it, not the example should be fixed in https://github.com/alvarotrigo/react-fullpage/pull/34

**Comment by alvarotrigo** [comment]
@cmswalker I was the one removing the styles :)

See my commit [here](https://github.com/alvarotrigo/react-fullpage/commit/eb687ac16542b852081b0289dde9fc6b288ff9be) on this same topic.

I removed it as otherwise we can't compile the example file?

```sh
cd examples/
npm install
npm run build
``` 

![45877564-952c7000-bd9e-11e8-8f66-c9fe136dbc95](https://user-images.githubusercontent.com/1706326/46356380-ebcd6000-c662-11e8-8d1f-87bcbf9946d5.png)

Am I missing something?

This would force developers to use a CSS loader instead of letting them deal with the CSS file as they want (bundle it, cache it etc)

Right now, we would have too add the following lines on the `examples/webpack.config.js` file so we can bundle the main.js file:

```javascript

      // STYLES
      {
        test: /\.css$/,
        use: [
          'style-loader',
          {
            loader: 'css-loader',
            options: {
              sourceMap: true,
            },
          },
        ],
      },
```

**Comment by cmswalker** [comment]
It depends how much work we want the user to do. When we run the build script, webpack bundles the css in js and creates style tags w/ js https://survivejs.com/webpack/styling/separating-css/

This is easier for the consumer but has drawbacks (flashing, larger js bundle)

We could have them manually include the styles themselves but it's just one extra step in adoption. Either way, let me know and I can make the change to the build/docs

**Comment by alvarotrigo** [comment]
I just changed the include to the `dist` file so no need is necessary on the webpack.config.

If you prefer using the same webpack config as the project and the `components` folder just let me know and I'll do the changes.
