### ISSUE TITLE
ScrollBar and ScrollOverflow don't work together

### ISSUE THREAD

**Issue by callihiggins** [alvarotrigo/react-fullpage#335]
### Description
If ScrollBar is set to true and ScrollOverflow in enabled, a long section cannot be scrolled

### Link to isolated reproduction with no external CSS / JS
[codesandbox.io](https://codesandbox.io/s/white-night-forked-dry02y)

### Steps to reproduce it
1. Scroll down to Component 2 ( long component)
2. Note that the section cannot be scrolled

### Versions 
react-fullpage 0.1.26

**Comment by alvarotrigo** [comment]
As expected.
You'll see a warning on the JS console saying:

> Options scrollBar:true and autoScrolling:false are mutually exclusive with scrollOverflow:true.

Both are not compatible.
