### ISSUE TITLE
Will there be a functional React component example coming soon?

### ISSUE THREAD

**Issue by eye-c** [alvarotrigo/react-fullpage#339]
All the Fullpage examples I see online use class components. Can Fullpage.js be used in a functional component?

**Comment by alvarotrigo** [comment]
Sure, check the hooks example:
https://github.com/alvarotrigo/react-fullpage/blob/master/examples/react/src/hooks.js

**Comment by eye-c** [comment]
Thank you, Alvaro. Great library
