### ISSUE TITLE
Unable to Scroll Vertically or Horizontally via Keyboard in Next.js

### ISSUE THREAD

**Issue by MichaelJohnson144** [alvarotrigo/react-fullpage#347]
### Description
I'm experiencing an issue with fullPage's "keyboardScrolling" horizontally/vertically between sections in Next.js where sections and slides wouldn't change after pressing a navigation key on my keyboard. I'd done some digging here and around the web to try and find a solution to this particular problem, tho to no avail; is there an existing solution to this that I'm ignorant to? 

### Link to isolated reproduction with no external CSS / JS
Not available at this moment in time. 

### Steps to reproduce it
1. Upon attempts to navigate the sections up/down/right/left via the keyboard nothing happens.  

### Versions 
[Chrome, Windows 10]

**Comment by alvarotrigo** [comment]
I'm unable to reproduce the issue on [this codesandbox](https://codesandbox.io/s/m34yq5q0qx).

Can you please provide an isolated reproduction in [Codesandbox](https://codesandbox.io/s/m34yq5q0qx) with no CSS or JS files external to fullPage.js and the minimum amount of HTML code? Use empty sections unless strictly necessary for the reproduction.

**Comment by MichaelJohnson144** [comment]
> I'm unable to reproduce the issue on [this codesandbox](https://codesandbox.io/s/m34yq5q0qx).
> 
> Can you please provide an isolated reproduction in [Codesandbox](https://codesandbox.io/s/m34yq5q0qx) with no CSS or JS files external to fullPage.js and the minimum amount of HTML code? Use empty sections unless strictly necessary for the reproduction.

Hi, Alvaro. I'd tried reproducing the issue on Codesandbox but was unfortunately unable to since I'm not a patron there; however, a similar problem--tho considered fixed and thus closed--can be seen and reproduced from [https://github.com/alvarotrigo/react-fullpage/issues/336]("gustavlrsn's") original's [https://codesandbox.io/s/react-fullpage-keyboard-scrolling-bug-enzwfq](here).

You'll notice that nothing happens upon attempting to navigate to another section via the keyboard. This issue, however, doesn't exist in my React version

**Comment by alvarotrigo** [comment]
> I'd tried reproducing the issue on Codesandbox but was unfortunately unable to since I'm not a patron there;

You don't need to be a patreon. Just fork it and save your new sandbox.

I'm not able to reproduce the issue in the [Next.js example](https://github.com/alvarotrigo/react-fullpage/tree/master/examples/next) that comes with react-fullpage.


> can be seen and reproduced from ["gustavlrsn's"](https://github.com/alvarotrigo/react-fullpage/issues/336) original's [here](https://codesandbox.io/s/react-fullpage-keyboard-scrolling-bug-enzwfq).

The author said he can no longer reproduce the issue in his machine. 
Codesandbox uses an iFrame that might be messing up with fullPage.js keyboard events.

**Comment by MichaelJohnson144** [comment]
Hi, Alvaro! I'd seen the cause of the issue; it was due to developing in dev mode in Next.js; this issue goes away in prod mode.

**Comment by alvarotrigo** [comment]
I'm glad you figured it out ;)

**Comment by SKYnSPACE** [comment]
Disabling Strict Mode by setting `next.config.(m)js` solved the issue in my case.

```
module.exports = {
  reactStrictMode: false,
}
```

**Comment by alvarotrigo** [comment]
> Disabling Strict Mode by setting next.config.(m)js solved the issue in my case.

Interesting...  thanks for the tip! 👍
