### ISSUE TITLE
on my development domain shows Unlicensed fullPage.js Extension

### ISSUE THREAD

**Issue by mishachto** [alvarotrigo/react-fullpage#349]
I bought both parallax license and fullpage.js license but I still see this alert.

licenseKey
and 
parallaxKey

Both of these fields are filled

PS and there is also a bug that my background is loaded only when you click on it, although there is a background in the css properties

**Comment by alvarotrigo** [comment]
For questions regarding extensions please use the [contact form](https://alvarotrigo.com/contact/).

**Comment by mishachto** [comment]
@alvarotrigo i can't send massage 
![image](https://user-images.githubusercontent.com/50331015/186441087-1707eeb5-d3a9-491e-9ba9-20e1acb4d399.png)
infiniti  loader and all....

**Comment by alvarotrigo** [comment]
That's weird. 
What browser are you using?
Any error on the JS console?

**Comment by mishachto** [comment]
@alvarotrigo Google 

Very many erros in  JS console...
![image](https://user-images.githubusercontent.com/50331015/186447832-59039713-275a-4350-8ce0-b3dfd4b077c5.png)

![image](https://user-images.githubusercontent.com/50331015/186447846-6695fbca-cf89-4b96-9bfa-23d65cede499.png)

**Comment by alvarotrigo** [comment]
Many of those seem to be caused by your Adblocker extension
![image](https://user-images.githubusercontent.com/1706326/186448470-59f11300-86f9-4937-9031-0f349d26ecbe.png)

Any relevant error after pressing the send button?

**Comment by mishachto** [comment]
@alvarotrigo Adblocker off 
but , same 
![image](https://user-images.githubusercontent.com/50331015/186449057-182d4cc8-4c79-431d-bbab-2eb71b2e4207.png)

**Comment by mishachto** [comment]
@alvarotrigo the same in incognito

**Comment by alvarotrigo** [comment]
I'm unable to reproduce the issue...
Would you be so kind to check the "Network" tab in Chrome Dev tools and see what you get on the ajax response after clicking the send button? :) 

Anyways, you can open a ticket through this form too:
[alvarotrigocomhelp@fullpage.freshdesk.com](https://fullpage.freshdesk.com/support/tickets/new)

**Comment by mishachto** [comment]
@alvarotrigo any way.
I send to https://fullpage.freshdesk.com/support/tickets/new .

Wait for your answer 
and sorry ...

**Comment by mishachto** [comment]
@alvarotrigo the second question is irrelevant
