### ISSUE TITLE
Fullpage.js and infinite scroll

### ISSUE THREAD

**Issue by FrancoisSoler** [alvarotrigo/react-fullpage#350]
Hello,

I'm trying to set up FullpageJs in my React app with infinite scroll. It's main purpose is to display an infinite flow of posts from WordPress
I'm using a framework to do the infinite scroll. It works by fetching the next posts to display once the scroll bar is close enough from the bottom, and then add the next post in the DOM, under the first post inside the parent div. 
So my question is how should I proceed to make FullpageJs works with my infinite scroll that adds a new div to the DOM on scroll ? 

here is my post-list components 

`  <Box className="boxWrapper"">

      <ReactFullpage
        //fullpage options
        licenseKey='my-license-key'
        scrollOverflow={true}
        verticalCentered={true}
        render={({ state, fullpage_api }) => {
          return (

            <ReactFullpage.Wrapper >
             // loop for the infinite scroll
              {posts.map(({ key, link, isLast, Wrapper, i }) => (

                <Wrapper key={key} className="section fp-auto-height" >
                  <Box >

                    <Post
                      post={post}
                      postData={postData}
                      link={link}
                      catId={catId}
                      posts={posts}
                      isLast={isLast}
                      key={key}
                    />

                    <PostPrevInfinite
                      bgColorArticle={bgColorArticle}
                      nextImgArray={nextImgArray}
                      // display={isLast ? "none" : "flex"}
                      className="PostPrevInfinite"
                      isSponso={isSponso}
                    />

                    {!isLast && <hr />}
                  </Box>
                </Wrapper>
              ))}

            </ReactFullpage.Wrapper>

          );
        }}
      />
      < Container
        css={css`
          background: ${bgColorArticle};
        `}
      >
        {isFetching && <Loading />}
        {
          (isLimit || isError) && (
            <Button
              onClick={fetchNext}
              css={css`
              background: ${colorsHover};
              transition: all 0.3s ease-in-out;
              &:hover {
                transform: scale(0.9);
              }
            `}
            >
              {isError ? "Essayer à nouveau" : "Charger plus"}
            </Button>
          )
        }
      </Container >
    </Box >
  );
};`

each section is a post loaded with infinite scroll
![div](https://user-images.githubusercontent.com/52791728/187813100-ec0b28e9-0fd9-4e7f-9b60-84f8a9a20c16.PNG)

thanks for reading

**Comment by alvarotrigo** [comment]
What's exactly the problem?
Can you replicate it on a codesandbox?

**Comment by alvarotrigo** [comment]
> make Fullpage know that a new section has been generated.

You don't have to.
The latest version of the react-fullpage component (version 0.1.27) will detect new sections/slides automatically and update accordingly.

>  I don't know how to make Fullpage allow to scroll enough to load the next post a

You'll have to use `scrollBar:false` and `fitToSection:false` to be able to detect the scrolled position on the page.

**Comment by alvarotrigo** [comment]
> So do I have to use rebuild() each time the infinite scroll fetch and put in the DOM a new post ? If so, how would you do it ?

I don't think so. 
Check [the example](https://github.com/alvarotrigo/react-fullpage/tree/0.1.23/examples) folder and see how it works there.

I'll close the issue as this is beyond the scope of the kind of support we provide here.
