### ISSUE TITLE
Incorrect license key in development environment for GatsbyJS

### ISSUE THREAD

**Issue by yiuhoward** [alvarotrigo/react-fullpage#368]
Hi,

I have a problem with the license key of fullpage react. The console complains about the license key is incorrect. But the production build on Netlify didn't encounter any error. I have bought a lifetime personal license key.

### Description
The issue only happens in development environment 

### Versions 
react: ^16.8.6
gatsby: ^3.14.6
@fullpage/react-fullpage: ^0.1.17

**Comment by alvarotrigo** [comment]
Make sure to update to react-fullpage 0.1.30 which uses fullPage.js version 4.
