### ISSUE TITLE
How to set scrollOverflowOptions for click event propagation?

### ISSUE THREAD

**Issue by jwongbandue** [alvarotrigo/react-fullpage#37]
Hi there!

I've found that click events will not work when setting `scrollOverflow: true` in desktop or mobile. Is there a way to pass scrollOverflowOptions as per [this thread](https://github.com/alvarotrigo/fullPage.js/issues/2035) and [this solution](https://stackoverflow.com/questions/22330419/submit-button-in-form-doesnt-work-with-iscroll)?

**Comment by alvarotrigo** [comment]
This should be a question for fullPage.js repository and not for the react one, as you can probably reproduce the issue without using react-fullpage too.

It has been treated multiple times on the fullpage.js repository forum, as this is a well known iScroll issue. 
Try reading and searching for solutions [in here](https://github.com/alvarotrigo/fullPage.js/issues?q=is%3Aissue+iscroll+click+is%3Aclosed).

Here's a similar issue regarding input forms:
https://github.com/alvarotrigo/fullPage.js/issues/2634
