### ISSUE TITLE
scrollOverflow v4 autoScrolling is not smooth

### ISSUE THREAD

**Issue by CoDe-8-ph** [alvarotrigo/react-fullpage#371]
### Description

I'm testing the scrollOverflow behavior. up to v3, I can move smoothly to the next section as shown in the Example, but in v4, it stops at the bottom of the section and does not move to the next section unless I scroll again.

In v4, it seems that importing the vendor file is no longer required, as shown below.

> 6. The option scrollOverflowOptions has been removed
> Because fullPage.js won't use the external vendor anymore, this option was also removed.

Or is there some other option that needs to be set?

[Example]
https://alvarotrigo.com/fullPage/examples/scrolling.html
https://codesandbox.io/s/ym2mrlz9k1?file=/src/index.js

[v4 testing codesandbox]
https://o7z02g-3001.preview.csb.app
https://codesandbox.io/p/github/CoDe-8-ph/fullpage.js/scrollOverflow?file=%2Fpages%2Findex.tsx

### Versions 
Next.js: 13.0.4
React: 18.2.0
@fullpage/react-fullpage: 0.1.31

**Comment by alvarotrigo** [comment]
This is actually [a bug fix](https://github.com/alvarotrigo/fullPage.js/issues/941) in itself, not a bug :) 

This behavior fixes very annoying issues with kinetic scrolling devices such as trackpads and some mouses like the Apple magic mouse or Logitech MX Master 3.

It is preventing unwanted scrolls on very sensitive devices, which results in having to scroll twice once reached the bottom. Which I believe is not a huge deal.
