### ISSUE TITLE
Determine when user scrolls to bottom of section when scrollOverflow={true}

### ISSUE THREAD

**Issue by maddleline** [alvarotrigo/react-fullpage#373]
Is there a way to determine when a user has hit the bottom of a scrollOverflow section? Normally I would compare the scroll position to the height of the scroll area, but I can't find a way to get the height of the scroll area.

```
          onScrollOverflow={(section, slide, position, direction) => {
            // how can I get the max value of position to compare against?
            console.log("position", position);
          }}
```

**Comment by alvarotrigo** [comment]
You can probably use the [`beforeLeave` callback](https://alvarotrigo.com/fullPage/docs/#beforeleave-origin-destination-direction-trigger) for that.

Or you can just get the height of the scrollable section and check by yourself if you reached the bottom:
https://stackoverflow.com/a/876134/1081396

**Comment by maddleline** [comment]
Got it, thank you!

**Comment by alvarotrigo** [comment]
Glad it helped!
