### ISSUE TITLE
Random behavior with a GraphQL request (Gatsby)

### ISSUE THREAD

**Issue by thomas-rx** [alvarotrigo/react-fullpage#382]
### Description
Demo : https://63a9a9f0ceb41a148500d333--glowing-mermaid-038425.netlify.app

Index page code : https://pastebin.com/duWKu50P
Projects code : **https://pastebin.com/DHiU5jB9** (Section are here)

### Steps to reproduce it
1. Make a GraphQL request with Gatsby.
2. Loop over the results of the query to create each section.

**Comment by alvarotrigo** [comment]
Can you try to isolate the problem by removing any vendor component external to fullPage.js?

If you can't, try using the fullPage.js option: `scrollBar: true` and see if that fixes the issue.
