### ISSUE TITLE
License not working in website

### ISSUE THREAD

**Issue by guillermo-t3** [alvarotrigo/react-fullpage#383]
### Link to isolated reproduction with no external CSS / JS
In a code sandbox the license key works, and hence there's no watermark, see image: 
![CleanShot 2023-01-04 at 20 29 35](https://user-images.githubusercontent.com/107854657/210634636-2e6b545e-bb71-464b-b699-16a548226a58.png)

On my client's website with the same license key that seemed to work on codesandbox I can't get rid of the watermark: https://inckd-git-develop-thirty3.vercel.app/#footer

### Versions 
"@fullpage/react-fullpage": "0.1.27" on the codesandbox seems to work, but breaks my website (I'm using the "scrollBar" property and it doesn't seem to work the same as in v0.1.31). 

If I use "@fullpage/react-fullpage": "^0.1.31" then my website works as intended, but the water mark appears

**Comment by alvarotrigo** [comment]
Make sure to disable the credits using the credits option:
https://alvarotrigo.com/fullPage/docs/#:~:text=sections%20or%20slides.-,credits,-.%20(default
