### ISSUE TITLE
Issues with touch events in components used inside slides

### ISSUE THREAD

**Issue by karliyo** [alvarotrigo/react-fullpage#39]
I'm using a component inside one slide that has a select menu from react-select package.

It appears that touch events aren't reaching that. When I try to scroll up or down in select menu, default slide change behavior just happens.

I'm not able to produce this behavior in Chrome dev tools. Dragging down or to sides to change slides doesn't work in dev tools so select menu is fine.   
Unusual behavior appeared in Chrome 69.0.3497.100 on Pie.

**Comment by alvarotrigo** [comment]
> It appears that touch events aren't reaching that. When I try to scroll up or down in select menu, default slide change behavior just happens.

That seems to be a fullPage.js issue and not a react-fullpage.js one.
You can probably reproduce it without using react-fullpage. 

Check the normalScrollElements options on the fullPage.js docs:
https://github.com/alvarotrigo/fullPage.js
