### ISSUE TITLE
TypeError : t is not a function

### ISSUE THREAD

**Issue by Seol827** [alvarotrigo/react-fullpage#394]
### Description
I'm trying to add the extension. (for sure, I have license key and extension key)
I successfully imported "pluginWrapper", but I faced the error as follow.

##### error msg (Chrome)
![image](https://user-images.githubusercontent.com/83569413/219546002-b3bbe38f-0b38-4814-9d3b-a485176bf50f.png)

##### code
```
const pluginWrapper = () => {
  require('../static/fullpage.scrollHorizontally.min')
}
return (
  <ReactFullpage
        //fullpage options
        pluginWrapper={pluginWrapper}
        licenseKey={''}
        scrollingSpeed={1000} /* Options here */
        scrollHorizontally={true}
        scrollHorizontallyKey={''}
        render={({ state, fullpageApi }) => {
          return (
            <ReactFullpage.Wrapper>
              <div></div>
              <div
                className="section"
                id="bg0"
                style={{
                  backgroundImage: `url("/images/main/BG1.jpg")`,
                  backgroundRepeat: 'no-repeat',
                  backgroundSize: 'cover',
                }}
              >
                <p id="main-title">Home</p>
              </div>
              <div
                className="section"
                id="bg1"
                style={{
                  backgroundImage: `url("/images/main/BG2.png")`,
                  backgroundRepeat: 'no-repeat',
                  backgroundSize: 'cover',
                }}
              >
                <p>Section 2</p>
              </div>
            </ReactFullpage.Wrapper>
          )
        }}
      />
)
```
How can I solve this problem?

### Versions 
React v18.2.0
Next.js v12.2.0
Typescript v4.7.4

**Comment by alvarotrigo** [comment]
What version of react-fullpage.js are you using and what version of the scroll horizontally extension are you using?

**Comment by Seol827** [comment]
Actually I'm not in charge of purchasing that.
So I'm not sure about the version but my team manager bought a license this week.
I think the latest one.

**Comment by alvarotrigo** [comment]
Make sure they are using the latest version of react-fullge anyways. (v 01.33)
The fullPage.js purchase is totally independent of it.

Also, make sure they purchased the extension recently too. In this case the purchase date is important for the extension.

**Comment by Seol827** [comment]
@alvarotrigo I confirmed that @fullpage/react-fullpage => 0.1.33 version.
And the fullPage.js which has purchased is v3.
the basic usage is fine well, but I think the extension file(fullpage.scrollHorizontally.min.js) is problem.
How can I fix it?

**Comment by Seol827** [comment]
@alvarotrigo I fixed the problem today. First of all, I'm so sorry😥 . In my case, I just received the extension key and license key from manager. So I thought the extension key would be 'scrollHorizontallyKey'. but I found the link to get the 'real' scrollHorizontallyKey anyway. Thanks and sorry🙏!

**Comment by Seol827** [comment]
@alvarotrigo There is one more question. Can I remove the watermark? I found that in the last extension page, there is a fullpage watermark. my extension plan is "professional".

**Comment by alvarotrigo** [comment]
React 0.1.33 uses fullPage.js version 4.
The extension you got is for version 3, which won't be compatible with v4.

So you'll need to get the latest extension by purchasing it again from the <a href="https://alvarotrigo.com/fullPage/extensions/" target="_blank">fullpage.js extensions</a> page.

>  Can I remove the watermark? 

Sure, just use the `credits` option as stated [on the docs](https://alvarotrigo.com/fullPage/docs/#:~:text=sections%20or%20slides.-,credits,-.%20(default)

**Comment by Seol827** [comment]
@alvarotrigo 
> React 0.1.33 uses fullPage.js version 4.

If I downgrade for React 0.1.32, Can I use version 3 I already purchased?

**Comment by alvarotrigo** [comment]
You would need to downgrade at least 10 versions. To react-fullpage 0.1.23.
https://github.com/alvarotrigo/react-fullpage/releases/tag/0.1.23

But note that's no longer maintained nor supported so you'll be on your own there.

I would encourage you to purchase the extension for v4 again and use that latest version for both, fullPage.js and the extension.

**Comment by Seol827** [comment]
@alvarotrigo sorry about my typing mistake! For sure, I did downgrade to 0.1.23. Could you check my problem?

**Comment by Seol827** [comment]
@alvarotrigo version matching is so hard..😥 Anyway, I did downgrade to react-fullpage 0.1.23.
I confirmed the drag and move is doing well, but I could check the console msg.
![image](https://user-images.githubusercontent.com/83569413/220488825-fadbc28d-2d28-46d7-84f0-309d91781904.png)
![image](https://user-images.githubusercontent.com/83569413/220488884-9472290c-f264-4ef1-ad93-5b0ebf154e78.png)
my source code didn't changed at all. So there is 'licenseKey'.
The error didn't appear before I downgraded to 0.1.23.

And I already purchased for v3. So If I want to use for v4, Should I pay for twice....?

**Comment by Seol827** [comment]
@alvarotrigo
Finally I checked all versions.

![image](https://user-images.githubusercontent.com/83569413/220493329-10b5c727-2d85-4ed2-9bba-2d710a402f43.png)
![image](https://user-images.githubusercontent.com/83569413/220493404-1c5b1706-cdd5-4fab-865c-c2644adcd2c9.png)
---
fullpage => v4
extensions => v3
That is why I couldn't apply the extensions. right?
But I can't confirm the version of extensions through the payment page.
(https://alvarotrigo.gumroad.com/l/fullpageExtensionsBundle)
please, how I can get the extensions version for 4.
If I need a refund, I'm gonna do that.

**Comment by alvarotrigo** [comment]
Let's move to private. 
Can you use the [contact form](https://alvarotrigo.com/contact/) and share with us the email you used for the purchases?

This way it will be faster.

**Comment by Seol827** [comment]
@alvarotrigo I send the form via [contact form](https://alvarotrigo.com/contact/).
check that please.

**Comment by alvarotrigo** [comment]
Thanks 👍
