### ISSUE TITLE
moveTo api requires both section and slide

### ISSUE THREAD

**Issue by devAdrish** [alvarotrigo/react-fullpage#405]
### Description
I am using Next.js and Typescript. My code only have sections. When I try to use the **moveTo** api with passing only 1 argument, it works locally, although vscode shows error, but build fails.
On the fullpage.js documentation, you can see,  second argument is optional, and it should work fine without it. 
If I pass any value as the second argument, then it doesn't work.

![image](https://user-images.githubusercontent.com/83942036/226871973-8cb6f3f7-1a1b-4327-8df1-b017e49df8dd.png)

Here's the screenshot from fullpage.js docs
![image](https://user-images.githubusercontent.com/83942036/226873250-116b0bb3-50e1-454a-a214-7af7de1854ee.png)

When I try to build, I get
![image](https://user-images.githubusercontent.com/83942036/226872578-3ce8243b-9830-4641-883d-45c0f9245c86.png)

### Versions 
Fullpage version: 0.1.36

**Comment by alvarotrigo** [comment]
Thanks for reporting it!
There was a bug with the types. 

This has been fixed on the latest release 0.1.37! 🥳 
Enjoy!
