### ISSUE TITLE
beforeLeave Callback is not defined

### ISSUE THREAD

**Issue by devAdrish** [alvarotrigo/react-fullpage#408]
### Description
Using Typescript with Nextjs. `beforeLeave` is missing types. Its available in fullpage.js.

Although it works when running locally, fails on build.
![image](https://user-images.githubusercontent.com/83942036/228238248-28cc5fb5-1d2a-441a-b6b6-9bdd4e47832d.png)

### Versions 
Browser: Chrome 111.0.5563.111
Fullpage: 0.1.34
Node: 16.6.0

**Comment by alvarotrigo** [comment]
Thanks for reporting it!
The issue has been fixed on the latest release 0.1.38! 🥳
