### ISSUE TITLE
Child component containing 'sections' doesn't work when rendered via renderItems

### ISSUE THREAD

**Issue by chrisedington** [alvarotrigo/react-fullpage#410]
### Description

I'm using React Native Web (everything seems to work fine with fullpage.js), however I have a FlatList component inside the ReactFullpage component.

When I move the `div sections` into the main component, directly underneath the ReactFullpage, everything works fine.

However when using FlatList's `renderItem` which loads another component (the list of images for example) that contains the `div sections`, they cannot be found, and one sees the expected errors:

```
Cannot read properties of null (reading 'index')
Cannot read properties of undefined (reading 'destroy')
```

So I guess it's more of a generic question, not a bug related to Fullpage.js, but is there a way I can get `div sections` to work if they are contained in child components that are rendered by method like `RenderItem`?

**Comment by alvarotrigo** [comment]
> ### Description
> I'm using React Native Web (everything seems to work fine with fullpage.js), however I have a FlatList component inside the ReactFullpage component.
> 
> When I move the `div sections` into the main component, directly underneath the ReactFullpage, everything works fine.
> 
> However when using FlatList's `renderItem` which loads another component (the list of images for example) that contains the `div sections`, they cannot be found, and one sees the expected errors:
> 
> ```
> Cannot read properties of null (reading 'index')
> Cannot read properties of undefined (reading 'destroy')
> ```
> 
> So I guess it's more of a generic question, not a bug related to Fullpage.js, but is there a way I can get `div sections` to work if they are contained in child components that are rendered by method like `RenderItem`?

Nope.
fullPage.js [requires certain structure](https://alvarotrigo.com/fullPage/docs/#required-html-structure):

```html
<div id="fullpage">
    <div class="section">Some section</div>
    <div class="section">Some section</div>
    <div class="section">Some section</div>
    <div class="section">Some section</div>
</div>
```

Sections can't be wrapped.
