### ISSUE TITLE
getScrollY() is not a function

### ISSUE THREAD

**Issue by RexHung0302** [alvarotrigo/react-fullpage#417]
### Description
I use getScrollY() and getScrollX(), get this is not a function.

can find this api at doc where https://alvarotrigo.com/fullPage/docs/#getscrolly--getscrollx

### Steps to reproduce it
1. I use https://alvarotrigo.com/react-fullpage/
2. 
```
useEffect(() => {
    if (!window.fullpage_api) return;
    console.log(window.fullpage_api.getScrollY()); // This was failed
  }, []);
  ```

### Versions 
@fullpage/react-fullpage": "0.1.22

**Comment by alvarotrigo** [comment]
> ### Versions
> @fullpage/react-fullpage": "0.1.22

Update to the latest version 0.1.40 ;)

**Comment by RexHung0302** [comment]
Thank for reply~
