### ISSUE TITLE
Input tabulation

### ISSUE THREAD

**Issue by cYaha** [alvarotrigo/react-fullpage#42]
Hi, I have a problem with react-fullpage. How I have fixed [the problem of vannila fullpage](https://github.com/alvarotrigo/fullPage.js/commit/900cd4ee22f2bd4e7a4f5f97d05de7fb9fafe52a) in my react app?

**Comment by alvarotrigo** [comment]
The problem you talk about was fixed on fullPage.js version 3.0.2 as can be seen on [the last comment of the topic you mention](https://github.com/alvarotrigo/fullPage.js/issues/3296).

Just make sure to use the latest react-fullpage version 0.1.1
