### ISSUE TITLE
Content is not centered on mobile devices

### ISSUE THREAD

**Issue by quanvanbinh** [alvarotrigo/react-fullpage#420]
### Description
Hi alvarotrigo,

Hope you are doing well.

Recently I am facing a problem with mobile devices. I apply React Fullpage to the desktop and big sizes mobile devices (tablet) and only on the Landscape mode; other will be normal scroll behavior. React Fullpage is working well on desktop devices. But on tablets, the content is not centered when user swipe up. Swiping down is centered well. I am very sure that content smaller than the viewport and not scroll overflow.

PLease give me the instruction to resolve it. Thank you so much

https://github.com/alvarotrigo/react-fullpage/assets/18342357/e0d1efc5-4c13-47d1-acd5-35e9dd814abb

### Browser 
Safari and Chrome

**Comment by AtulPatidar1709** [comment]
👋 @quanvanbinh, I want to work on this issue, Can you please assign it to me.

**Comment by quanvanbinh** [comment]
> 👋 @quanvanbinh, I want to work on this issue, Can you please assign it to me.

It seems I am not able to assign this issue to anyone. PLease ask alvarotrigo

**Comment by quanvanbinh** [comment]
After reading documentation carefully, I found my missing at the configuration. Just do the configuration for bigSectionsDestination and it will be as I wanted.

So I would like to close this issue

**Comment by alvarotrigo** [comment]
@quanvanbinh glad you managed to solve the issue! ;)
