### ISSUE TITLE
Support for React version 18 / Next version 13

### ISSUE THREAD

**Issue by marcelcp** [alvarotrigo/react-fullpage#421]
Hello, just bought the license and trying to implement into our website.

<img width="1040" alt="Screenshot 2023-09-13 at 13 35 26" src="https://github.com/alvarotrigo/react-fullpage/assets/25145908/ea360cb4-5d8b-49c4-9888-74383795242d">
On the screenshot above, there are two issue

- Issue that i need to include `credits={}` meanwhile it has default value, but it still require me to include it and cant be resolved by initiate the default value also..

- By importing ReactFullpage, it does has render() return, does render() deprecated on React 18? is there any workaround..

### Ecosystem
"@fullpage/react-fullpage": "^0.1.40",
"react": "18.2.0",
"next": "13.4.4",
 "@typescript-eslint/eslint-plugin": "^5.50.0",
 "typescript": "5.0.4"

**Comment by marcelcp** [comment]
Need workaround to setup the project
add ./tsconfig.json:
    "allowSyntheticDefaultImports" : true,
add .package.json:
  "resolutions": {
    "@types/react": "18.2.7"
  },

**Comment by alvarotrigo** [comment]
You can find a working demo here that won't show those errors:
https://codesandbox.io/s/m34yq5q0qx
