### ISSUE TITLE
Can I also get an open license key?

### ISSUE THREAD

**Issue by jungsikjeong** [alvarotrigo/react-fullpage#422]
Can I also get an open license key?

**Comment by alvarotrigo** [comment]
You don't have to ask for it. 
You can read more about licenses [here](https://alvarotrigo.com/fullPage/help/which-fullpage-js-license-should-i-choose/).

And go to the <a href="https://alvarotrigo.com/fullPage/docs" target="_blank">fullpage.js documentation</a> to find what license key to enter.
