### ISSUE TITLE
official offsetSections Extension not working in combination with react-fullpage

### ISSUE THREAD

**Issue by vitrinekast** [alvarotrigo/react-fullpage#425]
I'm unable to get the offsetSections extension to work out of the box using react-fullpage.

### Description
As soon as the user starts scrolling, i get the following error:
`Uncaught TypeError: s.offsetSections.getSectionPosition_ is not a function`

![Screenshot 2023-09-29 at 12 47 33](https://github.com/alvarotrigo/react-fullpage/assets/8696358/46979c72-169b-49bf-8a85-9b1d99b6af3a)

using the following isolated setup for the page (copy paste from the delivered example html file)
```
"use client";

import React from "react";
import ReactFullpage from "@fullpage/react-fullpage";

const pluginWrapper = () => {
  require("../../lib/fullpage.offsetSections.min.js");
};

export default function Fullpage() {
  return (
    <ReactFullpage
      pluginWrapper={pluginWrapper}
      licenseKey={"the-key"}
      offsetSections={true}
      render={({ state, fullpageApi }) => {
        return (
          <ReactFullpage.Wrapper>
            <div className="section" data-percentage="90">
              <div className="slide">
                <h1>Section 1</h1>
              </div>
              <div className="slide">
                <h1>Slide 1.2</h1>
              </div>
              <div className="slide">
                <h1>Slide 1.3</h1>
              </div>
            </div>
            <div className="section"-percentage="20" data-centered="true">
              <di className="intro">
                <h1>Section 2</h1>
                <p>This section is using `data-percentage="80"`.</p>
                <p>If you don't want to center it vertically, you could use `data-centered="false"`. See section 4.</p>
              </di>
            </div>
          </ReactFullpage.Wrapper>
        );
      }}
    />
  );
}
```

### Possible fix?
To try something, i've changed within the delivered fullpage.offsetSections.min.js `(t.getSectionPosition...` to `(t.getSectionPosition_`, and that seems to have done the trick, as far as i can see now. 
 
Doesn't seem like a very safe solution, but at least i'll be able to use the package for now. Will be great if this can be fixed for the next user! (Or, if you could let me know if this is a safe bet to use in production)

### Versions 
- fullpage.js Offset Sections Extension 0.0.4 
- @fullpage/react-fullpage": "^0.1.40",
- chrome 117 on macbook desktop device

**Comment by alvarotrigo** [comment]
The latest version of Offset Sections is 0.1.2. 
It seems you are using a very old one or that you haven't purchased it.

You can get it on the <a href="https://alvarotrigo.com/fullPage/extensions/" target="_blank">fullpage.js extensions</a>. 

If you still having problems with the latest version, feel free to use the [contact form](https://alvarotrigo.com/contact/) and send us an email using the email used for the purchase of the extension.

**Comment by alvarotrigo** [comment]
Apologies for the late reply btw!! 🙏
