### ISSUE TITLE
Scrolling error

### ISSUE THREAD

**Issue by Seol827** [alvarotrigo/react-fullpage#428]
Hello, I got an error with scrolling.
The 'Header(component)' has elements with `<Link className='' onClick={linkHandler}>OOOO OOOO기술</Link>`, `<button className='' onClick={() => navigate('/test')}>채용</button>`.
- click a 'button' element 
- move that page("/test")
- a lot of downscrolling (in the '/test' page)
- click a 'Link' element , and returned to main page(fullpage).
- the scrolling is not working (Sometimes.)

#### public repo
- https://github.com/Seol827/fullPage.git ("dev" branch)

#### my environment
- React ^18.2.0
- @fullpage/react-fullpage ^0.1.40

**Comment by alvarotrigo** [comment]
Can you provide an isolated reproduction in [Codesandbox](https://codesandbox.io/s/m34yq5q0qx) with no CSS or JS files external to fullPage.js and the minimum amount of HTML code? Use empty sections unless strictly necessary for the reproduction.

**Comment by alvarotrigo** [comment]
If you can provide the reproduction on jsfiddle or codepen, without even using React, that'd be even better :)
