### ISSUE TITLE
Anchor automatic scrolling after reload doesn't seem to work.

### ISSUE THREAD

**Issue by anshuraj** [alvarotrigo/react-fullpage#44]
After reload, the slides are not scrolling automatically to the anchor mentioned in the url. Is there any work around for that?

**Comment by alvarotrigo** [comment]
Thanks for reporting it! 
We'll investigate it!

**Comment by anshuraj** [comment]
I had to switch back to v0.0.6 where it works properly. Seems like there is some bug in latest build.

**Comment by alvarotrigo** [comment]
Probably related with https://github.com/alvarotrigo/react-fullpage/issues/31 and the creation of a temporal dummy section.

Will have to be fixed on the next fullpage.js release 3.0.4.

**Comment by cmswalker** [comment]
@anshuraj is this in production or development only?

**Comment by anshuraj** [comment]
Production

**Comment by Blackening999** [comment]
Wow, that's a bad news for my  site  :(

**Comment by cmswalker** [comment]
Could you provide a test repo that reproduces it?

**Comment by anshuraj** [comment]
@alvarotrigo @cmswalker Any update on this issue?

**Comment by alvarotrigo** [comment]
@anshuraj not yet.

**Comment by alvarotrigo** [comment]
This should be fixed now in 0.1.3.
