### ISSUE TITLE
FullpageJS React scrollOverflow w/ REST API WordPress

### ISSUE THREAD

**Issue by fervictoria** [alvarotrigo/react-fullpage#443]
### Dynamic content from API REST

Hi, first of all, thank you for this library. I love Fullpage and I've been using it since v2. I actually have a site using v3 and works perfectly (https://gyarados.red/)

Now I wanted to update that same site but now using React and WordPress as headless CMS. Everything seemed fine until I noticed that the scrollOverflow wasn't working as I wanted. I deduced it was related to fetching the content externally and that Fullpage was finishing rendering without the full sizes of that content (maybe I'm wrong). And after many attempts of using reBuild, afterLoad, suspense (react), I haven't figure it out. So I tried to reproduce it here:

First without the dynamic content to give you and idea:

https://codepen.io/fervictoria/pen/VYZmzPX

And then with the section that holds the WordPress posts:

https://codepen.io/fervictoria/pen/VYZmzZM

### Notes
1. I want to reproduce almost exactly the functions as in https://gyarados.red/
2. I have a production version already in https://victoria.rip/ because I used a timer, but I know it's not the perfect solution (I just purchased the v4 license for it and I'm using that version there).
3. I don't know what else to say. FYI I'm new at using React and English is not my main language, so sorry if this explanations are hard to understand.

I really hope you can help me! Thank you!

**Comment by alvarotrigo** [comment]
>  I deduced it was related to fetching the content externally and that Fullpage was finishing rendering without the full sizes of that content (maybe I'm wrong)

Yeah that's not the case anymore.
fullPage.js v4 doesn't need to know the size of the content to create the overflow unlike v3 and v2.

Can you explain what's the expected behavior and what's the behavior you are experiencing right now?
In what devices and in what web browsers can we reproduce it?

With your description I can't guess what's the problem. So it might be related with [this one](https://github.com/alvarotrigo/fullPage.js/issues/4674)?

> https://codepen.io/fervictoria/pen/VYZmzZM

This only shows a white page:
<img width="1522" alt="image" src="https://github.com/user-attachments/assets/f188da64-5e37-43c5-91b8-3068860b885e" />

**Comment by alvarotrigo** [comment]
> * I have a production version already in https://victoria.rip/ because I used a timer, but I know it's not the perfect solution (I just purchased the v4 license for it and I'm using that version there).

If you want your list to be scrollable, you might want to check out the [normalScrollElements option](https://alvarotrigo.com/fullPage/docs/#normalscrollelements).

You don't need scrollOverflow, very probably.

**Comment by fervictoria** [comment]
The expected behavior is to have a scrollOverflow in the sections that are bigger than the viewport. That's why I always used that option (https://gyarados.red). But using it in this new website (React + REST API), I have this behavior:

https://victoria.rip/video.mp4

It mostly happens when scrolling right after you opened the website in any tab. This video is in a desktop using Firefox, but it happens aswell in Chrome. It also happens in iOS and Android. If I don't use fp-auto-height in the sections, it will do the same jump with only the viewport, if I use fp-auto-height it will do what it's in the video.

Sometimes works fine and sometimes this happens. And it works again if I resized the window manually.

I'll try to replicated it in my codepen.

**Comment by fervictoria** [comment]
I started from scratch and I made it work this time, I suspect I was fetching the content in the wrong way. I believe it's working perfectly now:

https://victoria.rip/

The only weird thing is the prev arrow. It acts like next arrow.

Thanks!

**Comment by alvarotrigo** [comment]
> The expected behavior is to have a scrollOverflow in the sections that are bigger than the viewport. That's why I always used that option (https://gyarados.red).

If you want fullpage.js to create the scroll for you, then remove `height: 100vh;` on `#tracklist`. 
This way, you are not letting the content overflow, and fullPage.js won't see the need to create any scrollbar.

If you do so, fullPage.js will then make the whole section scrollable (even on desktop).

However, if you just want the tracklist to be scrollable, then keep those styles and use the `normalScrollElements` option so the user can scroll it up and down (In both desktop and mobile)
