### ISSUE TITLE
Object doesn't support property or method 'scrollTo' in Microsoft Edge

### ISSUE THREAD

**Issue by khairendra** [alvarotrigo/react-fullpage#46]
Actually this bug is already fixed in here:
[Fullpage - bug on Edge - Object doesn't support property or method 'ScrollTo' #3417](https://github.com/alvarotrigo/fullPage.js/issues/3417)

But not applied in the latest @fullpage/react-fullpage npm package (probably when building the package not using fullpage.js v3.0.3+)
When i build it from the source with fullpage.js v3.0.3 the bug dissapear.

**Comment by alvarotrigo** [comment]
True! Thanks for reporting it!
It seems somehow [the dist file is using fullPage.js 3.0.2](https://github.com/alvarotrigo/react-fullpage/blob/v0.1.1/dist/react-fullpage.js#L108) although the dependency is set to use fullpage.js 3.0.3 on [package.json](https://github.com/alvarotrigo/react-fullpage/blob/v0.1.1/package.json).

**Comment by alvarotrigo** [comment]
I've fixed it in react-fullpage v0.1.2
