### ISSUE TITLE
Object doesn't support property or method 'scrollTo' in Microsoft Edge

### ISSUE THREAD

**Issue by 0261** [alvarotrigo/react-fullpage#48]
I'm creating react-fullpage project with create-react-app.

but I faced to the follwing error message.

I found [
Fullpage - bug on Edge - Object doesn't support property or method 'ScrollTo' #3417](https://github.com/alvarotrigo/fullPage.js/issues/3417) this.

I think this bug has been already fixed but it  doesnt’t work in @fullpage/react-fullpage version 0.1.19

**Comment by alvarotrigo** [comment]
You should be using the latest 0.1.2. (0.1.19 [doesn't even exist?](https://github.com/alvarotrigo/react-fullpage/releases))

**Comment by 0261** [comment]
thank you.
