### ISSUE TITLE
FAQ

### ISSUE THREAD

**Issue by KirstenStemmet** [alvarotrigo/react-fullpage#50]
Hey there, I'm having a bit of trouble trying to to put my licence key in for the licence I have. I'm working react and read from start to finish but can't seem to get the hang of it, could you maybe assist me with this if you don't mind please

**Comment by alvarotrigo** [comment]
You should be asking this question on [the fullPage.js repository](https://github.com/alvarotrigo/fullPage.js). As this is just a wrapper around fullpage.j.s

There you'll read in the docs how to use the `licenseKey` option.
