### ISSUE TITLE
Documentation: clarify how to pass fullpage.js options with an example

### ISSUE THREAD

**Issue by alvarotrigo** [alvarotrigo/react-fullpage#51]
Related with https://github.com/alvarotrigo/react-fullpage/issues/50 after following up the conversation in https://github.com/alvarotrigo/fullPage.js/issues/3452#issuecomment-429914460.

We are missing in the docs an example on how to pass options to fullPage.js (although it can be seen in the example folder).

I would suggest adding the 2 ways of doing it:

- Using the props object
- Using attributes.

**Comment by cmswalker** [comment]
The first line [here](https://github.com/alvarotrigo/react-fullpage#props) covers it, perhaps we could just add some more props to the examples in the readme?

**Comment by alvarotrigo** [comment]
Yes, having an example of usage would help for these cases.

**Comment by alexshyba** [comment]
Sharing my journey in trying to figure out where to put the license key :) I think the render props threw me off, was trying to set licenseKey `fullpageApi` for some reason... Would be great to add `licenseKey="insert-your-key-here"` by default on `<ReactFullpage />` for the samples in docs. Will make it clearer where to add the license. I haven't noticed these paragraph at first: 
>You can use any options supported by fullPage.js library as react props.
Props object can contain standard options as well as fullPage.js callbacks.

BTW, the library looks great, thank you!
