### ISSUE TITLE
Is conditional rendering of navigation and anchors available?

### ISSUE THREAD

**Issue by anshuraj** [alvarotrigo/react-fullpage#52]
I'm trying to display the navigation only on some slides. Is this possible? I couldn't find any reference to this in docs.

Can anchors be disabled for some slides?

**Comment by alvarotrigo** [comment]
Make use of [fullPage.js state classes](https://github.com/alvarotrigo/fullPage.js#state-classes-added-by-fullpagejs) or [callbacks](https://github.com/alvarotrigo/fullPage.js#callbacks) for that. 
Check [this video tutorial I did](https://www.youtube.com/watch?v=qiCVPpI9l3M) regarding css3 conditions based on fullpage.js state classes.
