### ISSUE TITLE
iOS Safari BottomBar

### ISSUE THREAD

**Issue by zagoruyko-digital** [alvarotrigo/react-fullpage#57]
Bottom Bar doesn't hiding when your scroll down on iOS.

Is it possible to fix this somehow?
![img_bb029a1943d8-1](https://user-images.githubusercontent.com/40553144/47374241-e5348480-d706-11e8-9ac9-74cb00a89886.jpeg)

**Comment by alvarotrigo** [comment]
Please, open these kind of issues on [the library repository isself ](https://github.com/alvarotrigo/fullPage.js).
This is only a wrapper around fullpage.js and has nothing to do with these kind of issues.

And regarding your issue. No, the only way would be using the option `scrollBar:true` or `autoScrolling:false` to use the default scrolling behaviour of the browser. (and let the browser do whatever it wants, which is usually hide the bar on scroll down, show it on scroll up (on iOS))
