### ISSUE TITLE
[Question] How to set License for the fullpage.js

### ISSUE THREAD

**Issue by Vbubblery** [alvarotrigo/react-fullpage#58]
Hello,

There is an error appear in the client console:
`fullPage: Fullpage.js version 3 has changed its license to GPLv3 and it requires a licenseKey option. Read about it here: https://github.com/alvarotrigo/fullPage.js#options.`

```
new fullpage({
    licenseKey: 'YOUR_KEY_HERE'
});
```

Is there any way can add it easily?

**Comment by ahmedlhanafy** [comment]
@Vbubblery How did you solve this?

**Comment by alvarotrigo** [comment]
@ahmedlhanafy very probably acquiring a license from the [pricing page](https://alvarotrigo.com/fullPage/pricing/).

**Comment by alvarotrigo** [comment]
@cihanyasinkaya you are actually removing the last part of the error which is the URL that tells you all you need to know about the licenseKey option.

The full error is:

>   Fullpage.js version 3 has changed its license to GPLv3 and it requires a `licenseKey` option. Read about it here:
> https://github.com/alvarotrigo/fullPage.js#options

So, just go here and read :)
https://github.com/alvarotrigo/fullPage.js#options
