### ISSUE TITLE
[Error] Did not expect server HTML to contain a <div> in <div>.

### ISSUE THREAD

**Issue by Vbubblery** [alvarotrigo/react-fullpage#59]
My environment: Next.js+React.js+ReactStrap+Express

My code:

```jsx
class Index extends React.Component{
  constructor(props){
    super(props)
  }
   
  render(){
    const opts = {
      licenseKey: 'OPEN-SOURCE-GPLV3-LICENSE',
    };
    
    const FullpageWrapper = (opts)=>(
      <ReactFullpage
      {...opts}
      render={()=>{
        return(
          <ReactFullpage.Wrapper>
            <div className="section"><Alert color="primary">See you soon ........</Alert></div>
            <div className="section"><p>soon</p></div>
          </ReactFullpage.Wrapper>
        )
      }}
      />
    );
    
    return (
      <FullpageWrapper {...opts} />
    )
  }
}

```

But the client console throw a error:

```error
/_next/static/runtime/main.js:12752 Warning: Did not expect server HTML to contain a <div> in <div>.

__stack_frame_overlay_proxy_console__ @ /_next/static/runtime/main.js:12752
```

**Comment by cmswalker** [comment]
Thanks for reporting. Could you provide a repo with a reproduction?

**Comment by Vbubblery** [comment]
https://github.com/Vbubblery/dev_Nextjs_fp

**Comment by Vbubblery** [comment]
I checked online, there is someone who thinks the problem is on the wrapper.

**Comment by Vbubblery** [comment]
Okay, I get the solution.

The problem: the render result between the server side and the client is different.

Solution: Create a new Component for React-FullPage and then use the lazy-loading module to load it at the same times, disable the SSR option.

A new component:

```jsx
class Fullpage extends React.Component {
  constructor(props) {
    super(props);
  }
  render(){
    return(
    <ReactFullpage
      {...fullpageOptions}
      render={()=>{
        return(
          <ReactFullpage.Wrapper>
            <div className="section">1</div>
            <div className="section">2</div>
            <div className="section">3</div>
            <div className="section">4</div>
            <div className="section">5</div>
            <div className="section">6</div>
          </ReactFullpage.Wrapper>
        )
      }}
      />)
  }
}
export default Fullpage;
```
load it lazyly and disable SSR:

`const DynamicComponentWithoutSSR = dynamic(() => import('../components/Fullpage'),{ssr: false})`

**Comment by Vbubblery** [comment]
If you have any better solution leave here or close it.
Thx

**Comment by cmswalker** [comment]
did you try https://github.com/alvarotrigo/react-fullpage#server-side-rendering ?

I'm thinking it will be an unnecessary step to manually require a certain bundle if we can update the "main" in package.json https://github.com/alvarotrigo/react-fullpage/blob/master/package.json#L10 to this https://github.com/alvarotrigo/react-fullpage/blob/master/components/index.js

**Comment by cmswalker** [comment]
Sorry for the confusion over the SSR implementations. You can require the standard library now as it defaults to common JS. I have added some example repos to help

See: alvarotrigo/react-fullpage#server-side-rendering
