### ISSUE TITLE
basic example not doing anything is it react-router-dom

### ISSUE THREAD

**Issue by andrewcodes404** [alvarotrigo/react-fullpage#60]
hi
`<button onClick={() => fullpageApi.moveSectionDown()}>Click me to move down</button>
`
doesn't really do anything and I have to scroll a few times before getting to page 2

I do have a license but swapped it for XXX, is it in the right place

**Comment by farisT** [comment]
I am having a similar issue with my next.js setup. Everything is working fine only the fullpageApi does nothing when im trying to access it.

`
import React from 'react';
import ReactFullpage from '@fullpage/react-fullpage/dist/react-fullpage-commonjs';

const opts = {
  licenseKey: 'OPEN-SOURCE-GPLV3-LICENSE',
};

const ProjectSlider = (props) => (
  <div className='slider'>
    <ReactFullpage
     {...opts}
      render={({ state, fullpageApi }) => {
        return (
          <ReactFullpage.Wrapper>
            {props.children &&
            <div className='section section--home '>
                {props.children}
                <button onClick={() => fullpageApi.moveSectionDown()}>Hello</button>
            </div>
            }
              <div className='section project--one'>
                  <span className='project__number'>1</span>
              </div>
              <div className='section project--two'>
                  <span className='project__number'>2</span>
              </div>
              <div className='section project--three'>
                  <span className='project__number'>3</span>
              </div>
            
          </ReactFullpage.Wrapper>
        );
      }}
    />
  </div>
  );

  export default ProjectSlider
`

**Comment by cmswalker** [comment]
This is related to ongoing hot reload issue in dev. You can see it working w react router here https://codesandbox.io/s/4708ozmyw

Basically w/ the hot reload issue the fullpage state gets messy when components are re-injected. For now you'll have to refresh manually but I'm still looking into it.

Also be aware that this package requires React 16+

**Comment by ngtrongdat** [comment]
> This is related to ongoing hot reload issue in dev. You can see it working w react router here https://codesandbox.io/s/4708ozmyw
> 
> Basically w/ the hot reload issue the fullpage state gets messy when components are re-injected. For now you'll have to refresh manually but I'm still looking into it.
> 
> Also be aware that this package requires React 16+

i experienced this issue too
In your demo above, the 'move down' button doesn't work right away. i have to click to it multiple times before it starts working. Is there any work around to this issue?
Thanks

**Comment by cmswalker** [comment]
Yes this should be ok now
