### ISSUE TITLE
Render prop "state" value only has initialized poperty and nothing else (direction, origin...)

### ISSUE THREAD

**Issue by dankobgd** [alvarotrigo/react-fullpage#61]
Hello,

I am having problems with the latest version `0.1.2` where the state obj is not working properly and only shows this value: `{initialized: true}`

Before i used `0.0.9` and it worked perfectly fine and i could console.log all these stuff about origin, direction, isLast and so on and then i could trigger my own logic based on it... 
Am i missing something, did something change or is this just a bug?

Here are the codesandbox examples:
version `0.1.2` with a bug: https://codesandbox.io/s/n7296zk87l
version `0.0.9` works fine: https://codesandbox.io/s/5v2nk6y0qn

**Comment by Osamasomy** [comment]
i have also facing same issu...!

**Comment by alvarotrigo** [comment]
Thanks for reporting it! We'll take a look at it!

In any case, remember you can still use the fullpage.js callbacks to access those values as can be seen in [the provided example](https://github.com/alvarotrigo/react-fullpage/blob/master/example/src/index.js#L8).

```javascript
class Fullpage extends React.Component {
  onLeave(origin, destination, direction) {
    // arguments are mapped in order of fullpage.js callback arguments
    // do something with the event
  }

  render() {
    return (
      <ReactFullpage
        anchors={['firstPage', 'secondPage', 'thirdPage']}
        onLeave={this.onLeave.bind(this)}
        render={({ state, fullpageApi }) => {
...
...
```

**Comment by cmswalker** [comment]
@dankobgd @Osamasomy the state object only hands back what you subscribe to via callbacks. If you don't pass any callbacks (subscribers) all you get back is initialized.

**Comment by alvarotrigo** [comment]
@cmswalker I guess we can close this issue?
Do we need to clarify anything about it in the docs?
