### ISSUE TITLE
Support for SSR / Next.js? 

### ISSUE THREAD

**Issue by johnathan-terralogic** [alvarotrigo/react-fullpage#70]
Was wondering if there was a workaround for making react-fullpage work with an SSR framework like Next.js?  The error I'm getting when I imported react-fullpage in a Next app was that 'window' was undefined, which is understandable since 'window' isn't available for SSR.
react-fullpage: version: 0.1.3

**Comment by tomiiide** [comment]
Try importing the common js version.

Change your import to this.
`import ReactFullpage from "@fullpage/react-fullpage/dist/react-fullpage-commonjs"`

**Comment by cmswalker** [comment]
Sorry for the confusion over the SSR implementations. You can require the standard library now as it defaults to common JS. I have added some example repos to help

See: alvarotrigo/react-fullpage#server-side-rendering
