### ISSUE TITLE
Scrolloverflow doesn't work in next.js or SSR

### ISSUE THREAD

**Issue by tomiiide** [alvarotrigo/react-fullpage#71]
I get a `Window is not defined error` when trying to use `scrolloverflow` in next js.

I understand this is because there is no window object in SSR, however, is there a workaround or fix to get it to work, just like the main fullpage library works?

**Comment by tomiiide** [comment]
I made it work by copying the `scrolloverflow.min.js` file to `static` folder in the root of your project. 
Then linked it directly in `pages/_document.js` like:

`<script src="./../static/scrolloverflow.min.js" />`

Works till i find a better way.

**Comment by cmswalker** [comment]
Yes this is an unfortunate part of the plugins ATM. For now you could do a dynamic import based on window

```jsx
componentDidMount() {
	if (typeof window !== 'undefined') {
       require('fullpage.js/vendors/scrolloverflow');
    }
}
```

I'm going to leave this issue open as I think the react component should expose a method that does this wrapping for you, that way the consumer doesn't need to worry about implementation details

**Comment by cmswalker** [comment]
@tomiiide this is now baked in on version `0.1.8`

you can see the example on how to use it here https://github.com/alvarotrigo/react-fullpage#examples
