### ISSUE TITLE
Putting in other library

### ISSUE THREAD

**Issue by denisbykovopen** [alvarotrigo/react-fullpage#86]

**Comment by denisbykovopen** [comment]
Hi! Sorry! Making issue for the first time! Can't you help with the problem of putting in other library https://github.com/erichbehrens/react-animated-slider. It's a stateless component which didn't work when i put it in section.

**Comment by alvarotrigo** [comment]
If you have any specific question about it, feel free to ask. 
But here we only provide support for react-fullpage. 

Try creating a codesandbox or a Stackblitz.

**Comment by denisbykovopen** [comment]
https://codesandbox.io/s/w1yy8p4l7

**Comment by denisbykovopen** [comment]
https://codesandbox.io/s/w1yy8p4l7

I just didn't know wherer to write to you. Deadline(... And i'm a newb in React. Thank you for answering.

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
пятница, ноябрь 30, 2018 2:14 дня, Álvaro <notifications@github.com> пишет:
