### ISSUE TITLE
source map in production build 

### ISSUE THREAD

**Issue by salvoravida** [alvarotrigo/react-fullpage#87]
https://github.com/alvarotrigo/react-fullpage/blob/master/dist/react-fullpage.js

"sources":["/Users/alvarotrigolopez/...."]

can you check build please?

Thanks
SAlvo

**Comment by alvarotrigo** [comment]
Thanks for reporting it!!

I've fixed it on the dev branch.
Can you please @cmswalker review it?

I've added `NODE_ENV=prod ` on the `build` script in `package.json`.

**Comment by cmswalker** [comment]
Lgtm

**Comment by alvarotrigo** [comment]
Ok! I'll close the issue then!

**Comment by alvarotrigo** [comment]
I've made a new release. Fixed in react-fullpage 0.1.10

**Comment by salvoravida** [comment]
great thanks!
