### ISSUE TITLE
Changing anchor color when leaving section

### ISSUE THREAD

**Issue by adhamshandle** [alvarotrigo/react-fullpage#89]
how to change anchor color when i leave current section so there won't be a color conflict?

**Comment by alvarotrigo** [comment]
Anchor color?
You mean the section's color?

That's a question for the fullPage.js repository. But basically:

Make use of [fullPage.js state classes](https://github.com/alvarotrigo/fullPage.js#state-classes-added-by-fullpagejs) or [callbacks](https://github.com/alvarotrigo/fullPage.js#callbacks) for that. 
Check [this video tutorial I did](https://www.youtube.com/watch?v=qiCVPpI9l3M) regarding css3 conditions based on fullpage.js state classes.
