### ISSUE TITLE
Current configuration causes issues for common React environment

### ISSUE THREAD

**Issue by danielimmke** [alvarotrigo/react-fullpage#9]
Hello,

I had an issue when I was trying to set this up with a React project I have using [https://github.com/facebook/create-react-app](url). It took me a bit to figure out, but the default Webpack configuration with that starter kit uses a package: https://www.npmjs.com/package/case-sensitive-paths-webpack-plugin

This causes this package to not work with the stock Create React App kit. To fix I had to eject the configuration and manually remove the package from the config file. It might be worth taking a look at where this error is being caused in the package.

So not directly an issue with the code, but thought it would be worth letting you know. Thanks for the plugin, it's a great help!

![screen shot 2018-08-03 at 2 52 33 pm](https://user-images.githubusercontent.com/1744366/43662012-56a68ec0-9732-11e8-9f52-e7014f980c74.png)

**Comment by alvarotrigo** [comment]
Fixed on the repository.
It will get pushed to npm or the next release!

**Comment by mahendrushivam** [comment]
Can you please release this next build early

**Comment by alvarotrigo** [comment]
Fixed now in fullpage-react 0.0.6
