### ISSUE TITLE
fixedElements hard-moved to body - react leaks!

### ISSUE THREAD

**Issue by salvoravida** [alvarotrigo/react-fullpage#90]
`//fixed elements need to be moved out of the plugin container due to problems with CSS3.
            if(options.fixedElements && options.css3){
                $(options.fixedElements).forEach(function(item){
                    $body.appendChild(item);
                });
            }
`

i think that this piece of fullpage.js is not well react compatible!

a rapid fix is to delete elements from body on ReactFullpage unMount or Container unMount.

Any idea?

Salvo

**Comment by alvarotrigo** [comment]
You won't have to use `fixedElements` as long as you place those elements outside the fullpage.js wrapper.

For example:


```html
<div id="my-menu"></div>  <!--    <--- outside the wrapper -->

<div id="fullpage">
   <div class="section">Section 1</div>
   <div class="section">Section 2</div>
   <div class="section">Section 3</div>
</div>
``` 

So not really something you have to worry about :)
Just avoid using the option.

**Comment by salvoravida** [comment]
ok thanks!

but how i can stop fullpage handle scroll in background while my fixed menu is ontop in full height?

seems that disabling body overflow does not stop fullpage.js to handle scroll events....

**Comment by alvarotrigo** [comment]
Yeap not an issue.
Just make sure to call `setAllowScrolling(false)` when opening the modal and `setAllowScrolling(true)` when closing it.

More about the method on the docs:
https://github.com/alvarotrigo/fullPage.js#setallowscrollingboolean-directions

**Comment by MysticQuest** [comment]
Hello. Following the example at the home page. I placed my sidebar element (see code bellow) and it works like a fixed element. If I just place it outside of the wrapper, inside the render function, it doesn't stay fixed. Thing is I want to use the fullpageApi.moveSection functions for my sidebar buttons and I can't access it. Is there a way I can do that? 
```
const App = () => (
  <div>
    <MYFIXEDSIDEBAR />  /*<--------*/
    <ReactFullpage
      //fullpage options
      licenseKey={"YOUR_KEY_HERE"}
      scrollingSpeed={1000} /* Options here */
      render={({ state, fullpageApi }) => {
        return (
          <div>
            <ReactFullpage.Wrapper>
              <div className="section container1">section1</div>
              <div className="section container2">section2</div>
            </ReactFullpage.Wrapper>
          </div>
        );
      }}
    />
  </div>
);
```

**Comment by alvarotrigo** [comment]
Can you please provide an isolated reproduction of your issue in codesandbox?

**Comment by MysticQuest** [comment]
Of course. Thank you so much for your precious time. Very new to webdev, apologies if there are any glaring mistakes. Here it is:
https://codesandbox.io/s/portfolio-y0e9p

**Comment by alvarotrigo** [comment]
@MysticQuest have you tried using the global variable instead: `fullpage_api`

**Comment by MysticQuest** [comment]
Thanks for the pointer!
Managed to make the button work with window.fullpage_api.moveTo(section_number)

**Comment by nerdophile** [comment]
Hello @alvarotrigo  new to Web dev, How can I pass fullPageAPI and state to my fixed element which is outside of the wrapper?

**Comment by alvarotrigo** [comment]
> Hello @alvarotrigo new to Web dev, How can I pass fullPageAPI and state to my fixed element which is outside of the wrapper?

Use the global object `fullpage_api` instead that lives on `window`
