### ISSUE TITLE
fullPage: Fullpage.js version 3 has changed its license to GPLv3 and it requires a `licenseKey` option. Read about it here:

### ISSUE THREAD

**Issue by hongwanzhang** [alvarotrigo/react-fullpage#92]
I use it in open source ,and send email ?how can I get license ?

**Comment by alvarotrigo** [comment]
If you've sent an email then you'll just have to wait for my answer. 
I'll eventually reply! I promise! :)

**Comment by CodingOni** [comment]
Thanks

**Comment by Alaamasoud** [comment]
@alvarotrigo Hi,
so I have purchased a hobby license, I've only got a pdf file?

how could I make it works?
