### ISSUE TITLE
Broken in IE11

### ISSUE THREAD

**Issue by DmacLoyaltyOne** [alvarotrigo/react-fullpage#93]
Open https://alvarotrigo.com/react-fullpage/ in IE11, getting the following error message and blank screen:

SCRIPT438: Object doesn't support property or method 'find'
main.js (22,80779)

**Comment by alvarotrigo** [comment]
Thanks for reporting it!
Seems to be a building issue.

@cmswalker perhaps related with adding `es2015 ` preset for react?

**Comment by cmswalker** [comment]
@DmacLoyaltyOne  Could you verify if it is working for your use case in @fullpage/react-fullpage@0.1.12

**Comment by alvarotrigo** [comment]
I can confirm it works now on IE 11.

**Comment by alvarotrigo** [comment]
Thanks for that @cmswalker ! 😉

**Comment by rossenv** [comment]
Hi,
For me it's not working in IE 11 (Windows 10, Dell XPS 15 9560 ) . Here https://alvarotrigo.com/react-fullpage/ there is white screen. There are errors in dev console:

```
[object Error]{description: "Object does...", message: "Object does...", name: "TypeError", number: -2146827850, stack: "TypeError: ..."}
SCRIPT438: Object doesn't support property or method 'find'
main.js (22,80779)
```

I tried local setup with @babel/polyfill than core-js. The result is no errors but cant scroll with my touch pad. Only fullpageApi.moveSectionDown() works as expected.

**package.json:**
```{
  "name": "xyz",
  "version": "0.1.0",
  "dependencies": {
    "@fullpage/react-fullpage": "^0.1.13",
    "react": "^16.8.5",
    "react-dom": "^16.8.5",
    "react-scripts": "2.1.8"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": "react-app"
  },
  "browserslist": [
    ">0.2%",
    "not dead",
    "not ie <= 11",
    "not op_mini all"
  ]
}
```
**App.js:**
```
import React, { Component } from 'react';
import ReactFullpage from '@fullpage/react-fullpage';

import logo from './logo.svg';
import './App.css';

class App extends Component {
  render() {
    return (
      <ReactFullpage
        licenseKey="MY-LICENSE-KEY"
        render={({ state, fullpageApi }) => {
          return (
            <ReactFullpage.Wrapper>
              <div className="section">
                <p>Section 1 (welcome to fullpage.js)</p>
                <button onClick={() => fullpageApi.moveSectionDown()}>Click me to move down</button>
              </div>
              <div className="section">
                <p>Section 2</p>
              </div>
            </ReactFullpage.Wrapper>
          );
        }}
      />
    );
  }
}

export default App;
```

**Comment by alvarotrigo** [comment]
> For me it's not working in IE 11 (Windows 10, Dell XPS 15 9560 with trackpad ) . Here https://alvarotrigo.com/react-fullpage/ there is white screen. There are errors in dev console:

I didn't update the demo page yet :)
I'll add it to my to-do list!
However you can test the [example in the repo](https://github.com/alvarotrigo/react-fullpage/tree/master/example). It should work as expected.

> Here https://alvarotrigo.com/fullPage/ there are no errors but still not working (can't be used with trackpad)

That's something you would have to report in [the fullpage.js repository](https://github.com/alvarotrigo/fullPage.js/issues). However [I don't think I'm able to reproduce the issue](https://github.com/alvarotrigo/fullPage.js/issues/3354) by using Browsertack.com

**Comment by alvarotrigo** [comment]
@rossenv demo page fixed!
https://alvarotrigo.com/react-fullpage/

**Comment by rossenv** [comment]
Hi Alvaro, thanks for your prompt response. 
I made some research and found that the problem is not in fullPage.js. It's bug in **IE 11** and **Edge**. The issue is reported in 2016 here:

https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/7134034/

The problem is with so called precision touchpads which are common in newer laptops nowadays. IE and the older versions of Edge report that there is support for wheel events but not fire such. There is no problem with older (Synaptics) touchpads. The bug is fixed in Edge some time ago but not in IE 11. This is the cause of weird reports in your and many other git repos for this issue. 
The bigger problem is that we can't detect this missing functionality and apply fallback only in this case. 
I personally will search UX workaround for ie11 with our designers.

**Comment by alvarotrigo** [comment]
> I made some research and found that the problem is not in fullPage.js. It's bug in **IE 11** and **Edge**. The issue is reported in 2016 here:

Good to know! Thanks for the research! :)

> BTW: maybe it is good idea to make a note somewhere in your readme about this fact

Yeah I guess I should! 

Probably best thing you can do is turn off `autoScrolling` when you detect they access the site using IE 11.
