### ISSUE TITLE
silentMoveTo function Not Working

### ISSUE THREAD

**Issue by szrozr** [alvarotrigo/react-fullpage#96]
silentMoveTo function cant be used like moveTo function, is there any useful way to use the function such as MoveTo function in Reactjs.

**Comment by alvarotrigo** [comment]
It seems to be working totally fine for me on the [CodeSandBox](https://codesandbox.io/s/m34yq5q0qx) when changing the button in the 1st section to:

 ```html
<button onClick={() => fullpageApi.silentMoveTo(2,1)}>
     Move down
 </button>```

**Comment by alvarotrigo** [comment]
Please provide an isolated reproduction in [jsfiddle](https://jsfiddle.net/alvarotrigo/ea17skjr/) or [Codepen](https://codepen.io/alvarotrigo/pen/qqabrp), with no CSS or JS files external to fullPage.js and the minimum amount of HTML code. Use empty sections unless strictly necessary for the reproduction.
